### ISSUE TITLE
Data loss while reading from DB

### ISSUE THREAD

**Issue by ForCraft2013** [dgraph-io/badger#1126] opened 2019-11-19 18:59 UTC
Hello. I have an issue. Badger loses data while reading data when app suddenly stops, via Ctrl+C (for example). And this happenes when I read data just through **db.View** (_read only mode_).

Go: 1.13.4
Badger: 2.0.0
Windows 10 build 1903

After stop, vlog file becomes too big (2 147 483 646 bytes aka 2 GB). And if i run app again, Badger gives an error
`During db.vlog.open: Value log truncate required to run DB. This might result in data loss`
And finally, If I run Badger with **WithTruncate(true)** option, data loses. Vlog file size becomes 20 bytes.

I want to use Badger in my app, but 'cause of this problem i can't. Any error/stop while reading can cause lossing data.

The problem can be reproduced with this code (Ctrl+C while program prints keys and values into console):

**read.go**
```
func main() {
        db, err := badger.Open(badger.DefaultOptions("tmp/badger").WithSyncWrites(true))
	if err != nil {
		log.Panic(err)
	}
	defer db.Close()

	err := db.View(func(txn *badger.Txn) error {
                opts := badger.DefaultIteratorOptions
                opts.PrefetchSize = 10
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.Key()
			err := item.Value(func(v []byte) error {
				fmt.Printf("key=%d, value=%s\n", k, v)
				return nil
			})
                        if err != nil {
				return err
			}
		}
		return nil
	})
        if err != nil {
		log.Panic(err)
	}
}
```

**write.go**
```
func main() {
        db, err := badger.Open(badger.DefaultOptions("tmp/badger").WithSyncWrites(true))
	if err != nil {
		log.Panic(err)
	}
	defer db.Close()

	seq, err := db.GetSequence([]byte("0"), 1)
	if err != nil {
		log.Panic(err)
	}
	defer seq.Release()

        file, err := os.Open("some_big_data_file.txt")
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	err := db.Update(func(txn *badger.Txn) error {
		for scanner.Scan() {
			line := []byte(strings.TrimSpace(scanner.Text()))
			if len(line) > 0 {
				id, err := seq.Next()
				if err != nil {
					return err
				}
				key := make([]byte, 8)
				binary.BigEndian.PutUint64(key, id)
				err = txn.Set(key, line)
				if err != nil {
					return err
				}
			}
		}
		return scanner.Err()
	})
        if err != nil {
		return err
	}
}
```

**Comment by shekarm** [comment] 2019-11-20 05:40
ForCraft2013,

Thank you for reporting the issue. I will see if one of our engineers can take a look at it. 

Shekar

**Comment by jarifibrahim** [comment] 2019-11-22 09:34
Hey @ForCraft2013 

>After stop, vlog file becomes too big (2 147 483 646 bytes aka 2 GB). And if i run app again, Badger gives an error
During db.vlog.open: Value log truncate required to run DB. This might result in data loss
And finally, If I run Badger with WithTruncate(true) option, data loses. Vlog file size becomes 20 bytes.

Badger uses vlog files to store data and vlog files are `memory-mapped`. On windows, we cannot map a file more than its size, so we increase the size of value log file (2 GB in this case). While closing the file we truncate it back to its original size. This happens only on windows. 

You were seeing data loss because you were inserting all entries in a `single transaction`. A transaction is saved when you commit it. Since you were inserting all entries in a single transaction, any crash would mean no data will be saved. I made a small change to your test and I don't see any data loss. Can you try the following test and confirm it, please?
```go
func TestDataLoss(t *testing.T) {
	readData := false
	opt := DefaultOptions("./badger-data").WithSyncWrites(true)
	if readData {
		opt.Truncate = true
	}
	db, err := Open(opt)
	require.NoError(t, err)
	defer db.Close()
	if readData {
		read(db)
	} else {
		write(db)
	}
}
// Write will insert 3 entries
func write(db *DB) {
	for i := 0; i < 2000; i++ {
               // It is important that we create different transactions for each request.
		err := db.Update(func(txn *Txn) error {
			key := []byte(fmt.Sprintf("%d", i))
			fmt.Printf("inserting k: %d\n", i)
			err := txn.Set(key, []byte("barValue"))
			if err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			panic(err)
		}
		// Crash DB after inserting 3 entries
		if i == 2 {
			fmt.Println("Poof! DB crashed!")
			os.Exit(0) // Use os.Exit instead of panic.
		}
	}
}
func read(db *DB) {
	err := db.View(func(txn *Txn) error {
		opts := DefaultIteratorOptions
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.Key()
			err := item.Value(func(v []byte) error {
				fmt.Printf("key=%s, value=%s\n", k, v)
				return nil
			})
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		log.Panic(err)
	}
}
```

Here's the output of the test
```

# First run with read set to false.
$ go test -run TestDataLoss -v
=== RUN   TestDataLoss
badger 2019/11/22 09:20:51 INFO: All 0 tables opened in 0s
inserting k: 0
inserting k: 1
inserting k: 2
Poof! DB crashed!
ok      github.com/dgraph-io/badger/v2  0.268s

# Second run with read set to true.
$ go test -run TestDataLoss -v
=== RUN   TestDataLoss
badger 2019/11/22 09:21:06 INFO: All 0 tables opened in 0s
badger 2019/11/22 09:21:06 INFO: Replaying file id: 0 at offset: 0
badger 2019/11/22 09:21:06 INFO: Replay took: 962.6µs
badger 2019/11/22 09:21:06 DEBUG: Value log discard stats empty
key=0, value=barValue
key=1, value=barValue
key=2, value=barValue
badger 2019/11/22 09:21:06 DEBUG: Storing value log head: {Fid:0 Len:0 Offset:185}
badger 2019/11/22 09:21:06 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2019/11/22 09:21:06 INFO: Running for level: 0
badger 2019/11/22 09:21:06 DEBUG: LOG Compact. Added 4 keys. Skipped 0 keys. Iteration took: 0s
badger 2019/11/22 09:21:06 DEBUG: Discard stats: map[]
badger 2019/11/22 09:21:06 INFO: LOG Compact 0->1, del 1 tables, add 1 tables, took 1.9953ms
badger 2019/11/22 09:21:06 INFO: Compaction for level: 0 DONE
badger 2019/11/22 09:21:06 INFO: Force compaction on level 0 done
--- PASS: TestDataLoss (0.02s)
PASS
ok      github.com/dgraph-io/badger/v2  0.278s
```

**Comment by ForCraft2013** [comment] 2019-11-22 11:38
arifibrahim, hello. i've tried your code and it's working fine. Even when I removed "crash db on third iteration" and increased number of inserts to 10000.
But when I modified my code to "one insert - one transaction", i still get an error. Maybe the problem in something different? Key-value encoding for example. It's wierd that your code is working fine but my code is not. Сonsidering that code base is the same.

**Comment by jarifibrahim** [comment] 2019-11-22 11:51
>But when I modified my code to "one insert - one transaction", i still get an error. 

@ForCraft2013 What kind of error?

>Maybe the problem in something different? Key-value encoding for example. It's wierd that your code is working fine but my code is not. Сonsidering that code base is the same.

It's hard to tell what might be going on without looking at the code. Can you share your code?

**Comment by ForCraft2013** [comment] 2019-11-22 12:31
@jarifibrahim, i've found the cause of the problem! If **value** length is more than **31 bytes** then  error occurs. 

In your example badger gives the error (without truncate options):

```
badger 2019/11/22 16:28:58 INFO: All 1 tables opened in 1ms
badger 2019/11/22 16:28:58 INFO: Replaying file id: 0 at offset: 847804
2019/11/22 16:28:58 During db.vlog.open: Value log truncate required to run DB. This might result in data loss
panic: During db.vlog.open: Value log truncate required to run DB. This might result in data loss
```

With truncate option:
```
badger 2019/11/22 16:30:10 INFO: All 1 tables opened in 1ms
badger 2019/11/22 16:30:10 INFO: Replaying file id: 0 at offset: 847804
badger 2019/11/22 16:30:10 INFO: Replay took: 2.0028ms
badger 2019/11/22 16:30:10 DEBUG: Value log discard stats empty
2019/11/22 16:30:10 Invalid value pointer offset: 20 greater than current offset: 20
badger 2019/11/22 16:30:10 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
panic: Invalid value pointer offset: 20 greater than current offset: 20
```

```javascript
func TestDataLoss(t *testing.T) {
	readData := false
	opt := DefaultOptions("./badger-data").WithSyncWrites(true)
	if readData {
		opt.Truncate = true
	}
	db, err := Open(opt)
	require.NoError(t, err)
	defer db.Close()
	if readData {
		read(db)
	} else {
		write(db)
	}
}
// Write will insert 3 entries
func write(db *DB) {
	for i := 0; i < 2000; i++ {
               // It is important that we create different transactions for each request.
		err := db.Update(func(txn *Txn) error {
			key := []byte(fmt.Sprintf("%d", i))
			fmt.Printf("inserting k: %d\n", i)
                        //32 bytes length and now it's not working
			err := txn.Set(key, []byte("barValuebarValuebarValuebarValue"))
			if err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			panic(err)
		}
		// Crash DB after inserting 3 entries
		if i == 2 {
			fmt.Println("Poof! DB crashed!")
			os.Exit(0) // Use os.Exit instead of panic.
		}
	}
}
func read(db *DB) {
	err := db.View(func(txn *Txn) error {
		opts := DefaultIteratorOptions
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.Key()
			err := item.Value(func(v []byte) error {
				fmt.Printf("key=%s, value=%s\n", k, v)
				return nil
			})
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		log.Panic(err)
	}
}
```

**Comment by danielmai** [comment] 2019-11-26 18:33
@ForCraft2013 Thanks for reporting and reproducing this data loss issue on Windows. Please email me (the email in my GitHub profile) and we can discuss the next steps for your data-loss bounty reward.

**Comment by ForCraft2013** [comment] 2019-11-27 06:23
> @ForCraft2013 Thanks for reporting and reproducing this data loss issue on Windows. Please email me (the email in my GitHub profile) and we can discuss the next steps for your data-loss bounty reward.

I've sent you an email. And I made my real email public in my GitHub profile so you can be sure that i'm writing to you. I'm really glad that problem will be solved soon.

**Comment by jarifibrahim** [comment] 2019-12-06 13:49
This has been fixed in badger via https://github.com/dgraph-io/badger/commit/969a8e86294e164180aabd630313a06b97827081 .

Thank you for helping with the issue @ForCraft2013 :tada:

**Closed by jarifibrahim** 2019-12-06 13:49 UTC
Labels: bounty/dataloss, kind/bug, platform/windows, priority/P0, status/confirmed
