### ISSUE TITLE
Panic during WriteBatch

### ISSUE THREAD

**Issue by adamstruck** [dgraph-io/badger#1058] opened 2019-09-30 18:27 UTC
### What version of Go are you using (`go version`)?

<pre>
go version go1.12.7 linux/amd64
</pre>

### What version of Badger are you using?

https://github.com/dgraph-io/badger/tree/v2.0.0-rc3

### What are the hardware specifications of the machine (RAM, OS, Disk)?

Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)
1.5 TB RAM
2.5 TB SSD 

### What did you do?

While bulk loading data into badger a panic was encountered. The default options for badger are being used. The process runs fine for several hours and then badger panics. Below are the code snippets that demonstrate how WriteBatch is being used in our code. 

https://github.com/bmeg/grip/blob/kvindex-bulkwrite-as/cmd/kvload/main.go#L82-L90
https://github.com/bmeg/grip/blob/kvindex-bulkwrite-as/kvgraph/graph.go#L128-L157
https://github.com/bmeg/grip/blob/kvindex-bulkwrite-as/kvi/badgerdb/badger_store.go#L137-L151

### What did you expect to see?

No errors. 

### What did you see instead?

A panic.

```
2019/09/26 23:47:04 Assert failed
github.com/dgraph-io/badger/y.AssertTrue
	/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190809121831-9d7b751e85c9/y/error.go:55
github.com/dgraph-io/badger.(*DB).updateHead
	/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190809121831-9d7b751e85c9/db.go:575
github.com/dgraph-io/badger.(*DB).writeRequests
	/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190809121831-9d7b751e85c9/db.go:667
github.com/dgraph-io/badger.(*DB).doWrites.func1
	/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190809121831-9d7b751e85c9/db.go:706
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

**Comment by jarifibrahim** [comment] 2019-10-01 04:49
@adamstruck Do you have any more badger logs?

**Comment by jarifibrahim** [comment] 2019-10-01 18:38
@adamstruck Yes, that would be helpful.
It would also be useful if you can give me steps to run https://github.com/bmeg/grip and reproduce the error.

**Comment by adamstruck** [comment] 2019-10-02 15:40
[Here](https://gist.github.com/adamstruck/772bd87f70384708f762a3a882300e08) is a snippet of the process again with debug level logging. Logs from badger contain `"namespace": "badger"`.  

I am beginning to think our loader script is using WriteBatch  incorrectly. A single WriteBatch transaction is being opened for loading the entirety of the database. 

I tried to replicate the error with [this script](https://gist.github.com/adamstruck/22f94e7a49ebe4fe0550e81a788327eb), but rather than getting a panic the program was killed when the available memory was exhausted. (Note: I ran this test on a machine with 12 cores, 60GB RAM).

**Comment by jarifibrahim** [comment] 2019-10-03 13:58
@adamstruck You program crashed with Out of Memory error because you were unnecessarily creating too many byte slices. With the following changes, write batch works fine
```diff
 func write(tx *badger.WriteBatch, n int, vsize int) {
+	key := make([]byte, 32)
+	val := make([]byte, vsize)
 	for j := 0; j <= n; j++ {
-		val := make([]byte, vsize)
 		_, err := rand.Read(val)
 		if err != nil {
 			log.Error("generate value:", err)
 			continue
 		}
-		key := make([]byte, 32)
 		_, err = rand.Read(key)
 		if err != nil {
 			log.Error("generate key:", err)
```

Also, please change the `MaxTableSize` to at least 110 MB. The `wb.Flush()` call might crash if you set the max table size to less than 110 MB.

**Comment by jarifibrahim** [comment] 2019-11-08 09:35
hey @adamstruck can you help me with the steps to run https://github.com/bmeg/grip so that I can reproduce the issue?

**Comment by adamstruck** [comment] 2019-11-08 18:15
Build grip binary:
```
$ git clone https://github.com/bmeg/grip.git
$ cd grip
$ make
```

Download the data and manifest from: https://bmeg.io/data/rc4/

Make vertex manifest: 

```
$ cat bmeg_file_manifest.txt | grep "Vertex" > vertex_manifest.txt
```

Run the loader:
```
grip kvload <graph-name> --vertex-manifest bmeg_file_manifest.txt 
```

**Comment by jarifibrahim** [comment] 2019-11-14 13:52
Hey @adamstruck I'm getting forbidden error on https://bmeg.io/data/rc4/ctrp/ (or any other link). Is there any other way to download the data? I was able to download the manifest file.

**Comment by jarifibrahim** [comment] 2019-11-18 13:54
Hey @adamstruck I need your help to reproduce the issue. How do I download the data files? I'm getting forbidden error.

It would also be helpful if you can make the following change in `badger/db.go` file
```diff
- y.AssertTrue(!ptr.Less(db.vhead))
+ y.AssertTruef(!ptr.Less(db.vhead), "ptr: %+v db.vhead: %+v", ptr, db.vhead)
```
and share the logs with me.

**Comment by adamstruck** [comment] 2019-11-18 16:22
Sorry for the delay, the permissions issues should be fixed. I'll make the change above and share the logs.

**Comment by jarifibrahim** [comment] 2019-11-22 11:12
Hey @adamstruck I couldn't run GRIP because of OOM error https://github.com/bmeg/grip/issues/222 . Is there any way I can reproduce the failure?

**Comment by adamstruck** [comment] 2019-11-22 16:03
I am aware of the OOM error and working on patching it. I have only been able to reproduce the error on our high memory (1.5 TB) machine mentioned in the original error report.

**Comment by adamstruck** [comment] 2019-11-25 16:18
As mentioned in https://github.com/bmeg/grip/issues/222:

The OOM error described above is due to a memory leak in badger's WriteBatch method. It appears that if you present the method will a large number of KV pairs where the value is large, that these pending writes accumulate in memory thus causing the OOM error.  Digging in your source code, I think that it has to due with the calculation in https://github.com/dgraph-io/badger/blob/3eb4e723d3ae4cdde80434ba8cf57b1d19c3fb38/structs.go#L154 that used to determine the overall size of the transaction.

**Comment by jarifibrahim** [comment] 2019-11-27 14:31
>The OOM error described above is due to a memory leak in badger's WriteBatch method. It appears that if you present the method will a large number of KV pairs where the value is large, that these pending writes accumulate in memory thus causing the OOM error. 

@adamstruck I've replied on the OOM issue. I don't agree that the OOM is because of badger. The following is the memory profile I had attached to the original issue on GRIP which doesn't even show badger https://github.com/bmeg/grip/issues/222#issue-527110504
```
Fetching profile over HTTP from http://localhost:8080/debug/pprof/heap
Saved profile in /home/ibrahim/pprof/pprof.grip.alloc_objects.alloc_space.inuse_objects.inuse_space.004.pb.gz
File: grip
Build ID: db26589919a25557fa7d0e00f5be9abd198900b6
Type: inuse_space
Time: Nov 22, 2019 at 3:40pm (IST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 11.08GB, 98.98% of 11.19GB total
Dropped 25 nodes (cum <= 0.06GB)
Showing top 10 nodes out of 28
      flat  flat%   sum%        cum   cum%
    5.60GB 50.02% 50.02%     5.60GB 50.02%  reflect.mapassign
    2.70GB 24.15% 74.17%     9.98GB 89.13%  github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue
    0.76GB  6.79% 80.96%     0.76GB  6.79%  github.com/bmeg/golib.ReadLines.func1
    0.75GB  6.73% 87.69%     0.86GB  7.69%  reflect.cvtBytesString
    0.41GB  3.69% 91.38%     0.41GB  3.69%  encoding/json.(*RawMessage).UnmarshalJSON
    0.24GB  2.12% 93.51%     0.24GB  2.12%  encoding/json.(*Decoder).refill
    0.21GB  1.87% 95.38%     3.13GB 28.00%  encoding/json.(*decodeState).object
    0.19GB  1.73% 97.10%     0.19GB  1.73%  reflect.Zero
    0.11GB  0.97% 98.07%     0.11GB  0.97%  reflect.New
    0.10GB  0.91% 98.98%     0.10GB  0.91%  github.com/golang/protobuf/jsonpb.unquote
(pprof) top -cum
Showing nodes accounting for 8717.24MB, 76.05% of 11463.14MB total
Dropped 25 nodes (cum <= 57.32MB)
Showing top 10 nodes out of 28
      flat  flat%   sum%        cum   cum%
         0     0%     0% 10568.13MB 92.19%  github.com/bmeg/grip/util.StreamVerticesFromFile.func1
         0     0%     0% 10568.13MB 92.19%  github.com/golang/protobuf/jsonpb.(*Unmarshaler).Unmarshal
         0     0%     0% 10568.13MB 92.19%  github.com/golang/protobuf/jsonpb.(*Unmarshaler).UnmarshalNext
         0     0%     0% 10568.13MB 92.19%  golang.org/x/sync/errgroup.(*Group).Go.func1
 2768.35MB 24.15% 24.15% 10217.65MB 89.13%  github.com/golang/protobuf/jsonpb.(*Unmarshaler).unmarshalValue
         0     0% 24.15%  5734.38MB 50.02%  reflect.Value.SetMapIndex
 5734.38MB 50.02% 74.17%  5734.38MB 50.02%  reflect.mapassign
  214.51MB  1.87% 76.05%  3210.01MB 28.00%  encoding/json.(*decodeState).object
         0     0% 76.05%  3210.01MB 28.00%  encoding/json.(*decodeState).unmarshal
         0     0% 76.05%  3210.01MB 28.00%  encoding/json.(*decodeState).value

(pprof) list github.com/bmeg/grip/util.StreamVerticesFromFile.func1
Total: 11.19GB
ROUTINE ======================== github.com/bmeg/grip/util.StreamVerticesFromFile.func1 in /home/ibrahim/Projects/grip/util/file_reader.go
         0    10.32GB (flat, cum) 92.19% of Total
         .          .     41:
         .          .     42:	for i := 0; i < runtime.NumCPU(); i++ {
         .          .     43:		g.Go(func() error {
         .          .     44:			for line := range reader {
         .          .     45:				v := &gripql.Vertex{}
         .    10.32GB     46:				err := m.Unmarshal(bytes.NewReader(line), v)
         .          .     47:				if err == io.EOF {
         .          .     48:					break
         .          .     49:				}
         .          .     50:				if err != nil {
         .          .     51:					log.WithFields(log.Fields{"error": err}).Errorf("Unmarshaling vertex: %v", line)
(pprof)  
```

@adamstruck I agree that the code here https://github.com/dgraph-io/badger/blob/3eb4e723d3ae4cdde80434ba8cf57b1d19c3fb38/structs.go#L153-L158 could cause an OOM but the issue on https://github.com/bmeg/grip/issues/222#issue-527110504 is not because of this piece of code.

**Comment by jarifibrahim** [comment] 2019-11-27 14:37
Unfortunately, I haven't been able to reproduce the original issue. I'm going to mark this issue as `not reproducible` and close it for now. @adamstruck If you face this issue again, please feel free to re-open.

As for the OOM issue you mentioned, I don't think it's an actual issue and we should do something about it. If you feel otherwise, please create a new issue for it and I'd be happy to help with it. :)

**Closed by jarifibrahim** 2019-11-27 14:37 UTC
Labels: area/crash, kind/bug, priority/P1, status/confirmed, status/more-info-needed
