### ISSUE TITLE
How to get the Previous key during Seek?

### ISSUE THREAD

**Issue by MeirionHughes** [dgraph-io/badger#712] opened 2019-02-13 11:53 UTC
I'm trying to make a general secondary index k<sup>B</sup>→ k<sup>A</sup> for many prefixed-sets k<sup>A</sup> → V where it is likely to "miss" and needs to return the nearest, i.e. [k<sup>A-1</sup>, k<sup>A+1</sup>]. It is them expected the calling iterator would choose to do interpolation of the values.

My problem is that badger I can't see anything that allows me to get that "previous" key during seeking. 

For example, I can forward iterate to k<sup>A</sup> and on a miss I will get k<sup>A+1</sup>. Is there a way to get the previous key k<sup>A-1</sup> after a `Seek` in badger?

The only solution I can think of at the moment is to run two iterators, one forward and one backward. If the forward iterator seek misses the searched key, then seek on the reverse iterator to find the other side. Support for two iterators is only available on the 2.0rc-1 release, so I'm wondering if a) there is a way to get the "last" entry during a seek, or b) toggle an existing iterator into reverse mode and back again?

**Comment by campoy** [comment] 2019-05-28 22:03
Closing this one as a duplicate of #786.

**Closed by campoy** 2019-05-28 22:03 UTC
Labels: area/documentation, kind/question, status/needs-attention
