### ISSUE TITLE
Bulk deletes fail when over 100 items

### ISSUE THREAD

**Issue by mperham** [dgraph-io/badger#369] opened 2017-12-19 17:53 UTC
Here's a test which:

1. Creates 200 items
2. Iterates over the DB and verifies we see 200 things
3. Deletes 200 items
4. Iterates over the DB and verifies we see 0 things

This test passes if the count is 99 and fails if 101 so there is a magical value of 100 at work here.

https://gist.github.com/mperham/d1b57b7a78ae06983076729af4f4a258

**Comment by deepakjois** [comment] 2017-12-20 08:26
This is a really strange bug. I can see all the delete operations making the way to the `writeRequests` method in `db.go`. At that point they are written to the memtable. I havent dealt with that part of the codebase too much so I am not sure what is the best way to debug it.

I am thinking of just parsing the files on disk and making sure the deletes are reflected there. If they are not, we can at least be sure the problem is between calling `writeRequests` and the process of writing it to a memtable.

**Comment by janardhan1993** [comment] 2017-12-20 08:40
Just noticed that key is not being copied before passing to delete. The item would be reused so the value of key can change by the time it's committed. Since default prefetchsize is 100, item won't be resued upto 100 values hence the issue.

**Comment by deepakjois** [comment] 2017-12-20 08:52
Sigh…yes I did not spot that.

@mperham If you modify your delete call from:

```Go
err := tx.Delete(it.Item().Key())
```

to 

```Go
key := make([]byte, len(it.Item().Key())
key := copy(key, it.Item().Key())
err := tx.Delete(key)
```

It should work.

I will add some documentation around copying keys and values.

**Comment by mperham** [comment] 2017-12-20 12:03
It would be useful to have a KeyCopy() API just like ValueCopy().

**Comment by mperham** [comment] 2017-12-20 17:59
ValueCopy makes it really obvious in the API that the user needs to think about the scope of the value.  I would argue Key needs the same.

I would also wonder if you should be performing Item caching in a write transaction.  Safer not to reuse Items in that case?

**Comment by manishrjain** [comment] 2018-03-01 03:35
So, the task here to add a `KeyCopy` api on transaction, correct?

**Comment by Niondir** [comment] 2018-03-10 00:11
Since `tx.Delete()` is not executed immediately but appends the `Entry` to `txn.pendingWrites[string(key)] = e`  I would argue to always copy the key inside `tx.Delete()`

This way the API stays simple and is less error prone. I can't judge the performance change here but consider it rather small.

**Comment by manishrjain** [comment] 2018-03-12 21:21
`string(key)` is doing a copy.

**Comment by janardhan1993** [comment] 2018-03-13 05:24
KeyCopy method is in master now.

**Closed by janardhan1993** 2018-03-13 05:24 UTC
Labels: enhancement, low-pri
