### ISSUE TITLE
go get github.com/dgraph-io/badger/...: no matching versions for query "latest"

### ISSUE THREAD

**Issue by cckumarr** [dgraph-io/badger#788] opened 2019-04-29 22:54 UTC
ran the go get command as mentioned in the readme
received the: no matching versions for query "latest"

GO111MODULE set to "on"

![Screen Shot 2019-04-29 at 16 55 59 PM](https://user-images.githubusercontent.com/3590592/56932112-b32e2180-6a9f-11e9-9c94-b9b13d1d004f.png)

**Comment by cckumarr** [comment] 2019-04-29 22:55
go get github.com/dgraph-io/badger/...
go: finding github.com/dgraph-io/badger/... latest
go get github.com/dgraph-io/badger/...: no matching versions for query "latest"

go version
go version go1.12.1 darwin/amd64

**Comment by jarifibrahim** [comment] 2019-05-03 09:42
@cckumarr Badger doesn't support Go Modules for now. We are working on adding go module support.
You could try setting `GO111MODULE=on` to `GO111MODULE=off` and `go get -v github.com/dgraph-io/badger` should work fine.

**Comment by campoy** [comment] 2019-05-28 22:46
Closing it as duplicate of #758

**Closed by campoy** 2019-05-28 22:46 UTC
Labels: kind/question
