### ISSUE TITLE
Deadlock on single-threaded, large writes, including reproducer

### ISSUE THREAD

**Issue by hillu** [dgraph-io/badger#410] opened 2018-01-26 16:33 UTC
Hi,

I am trying to implement an inverted index based on bitmaps stored in BadgerDB and have run into deadlock issues that seem similar to those described in #384. I have put together a [reproducer](https://github.com/hillu/badger-lockup-reproducer).

There are bulk writes that can become rather large and often need to be split across multiple transactions. I had also experimented with reducing the transaction size before hitting the `ErrTxnTooBig` error, but that has not helped in my case.

**Comment by manishrjain** [comment] 2018-01-26 23:14
I ran the reproducer, added some logs as well. But, it kept on going and all it did was freeze my laptop. I haven't been able to replicate the deadlock.

**Comment by hillu** [comment] 2018-01-27 03:19
@manishrjain Did the program ever reach entry 134?

**Comment by hillu** [comment] 2018-01-29 17:08
@manishrjain Would you like to share the log statements that you added?

**Comment by manishrjain** [comment] 2018-01-30 02:51
Sorry, haven't had a chance to investigate further. Let me get back.

**Comment by hillu** [comment] 2018-01-30 10:41
Meanwhile, I have been able to reproduce the issue with a few older versions of badger. It also happens with 1.2.0, 1.1.0, 1.0.0. (The test could not be run as-is using previous versions due to changes in 5ad4981c9a2940efe8bd052a2bda2d7a508d90c8.)

The program will use well over 5 GB virtual memory.

**Comment by hillu** [comment] 2018-01-30 12:20
I just discovered the `golang.org/x/trace` support and added a local http server to my reproducer. The last entries of the event trace lead me to think that something is going wrong as `(*DB).writeRequests` calls `(*DB).vlog.write`:
```
12:43:11.580872	 .  2705	... writeRequests called. Writing to value log
12:43:11.590391	 .  9519	... Writing to memtable
12:43:11.590401	 .    10	... 2 entries written
12:43:11.611276	 . 20875	... writeRequests called. Writing to value log
12:43:11.623989	 . 12713	... Writing to memtable
12:43:11.630259	 .  6269	... 1631 entries written
12:43:11.641416	 . 11157	... writeRequests called. Writing to value log
12:43:11.645462	 .  4046	... Writing to memtable
12:43:11.645478	 .    16	... 3 entries written
12:43:12.845980	1.200502	... writeRequests called. Writing to value log
```
These log output lines should correspond roughly to the event trace.
```
2018/01/30 12:43:11 entry 133, cardinality: 1630
2018/01/30 12:43:11 todo: 1630, done: 0
2018/01/30 12:43:11 Wrote 112722 bytes to values
2018/01/30 12:43:11 entry 134, cardinality: 92132
2018/01/30 12:43:11 todo: 92132, done: 0
```

**Comment by hillu** [comment] 2018-01-30 13:24
After adding a few more event trace points, I can show that `(*lockFile).doneWriting` fails to acquire the write lock (https://github.com/dgraph-io/badger/blob/39bfb9cbbe922c50a53aa839476d052b19eaa519/value.go#L155) and thus waits forever.

**Comment by janardhan1993** [comment] 2018-01-30 22:54
I was able to reproduce this, i have added a minimal example/test in ee3add86755215af0a4dde80ee6ef41446885c40. 
It happens when a transaction get takes a Rlock on the last value log file(item.value()) and the set causes the file size to cross valuelogsize threshold. Set is stuck on lock on the last value log file.

Since the Rlock is not released before discard is called it causes deadlock. @deepakjois  @manishrjain  We should probably reintroduce our older api(value used to take a callback) so that we can release the lock earlier.

**Comment by manishrjain** [comment] 2018-01-31 14:56
Could we fix this without changing the API? For e.g., by just continuing to write into the value log file, instead of trying to create a new one?

**Comment by MoZhonghua** [comment] 2018-02-02 00:19
Some thoughts:

Now, badger has three types of access type to vlog:
- A: lock for read-only, when call item.Value()
- B: lock for append-only, when txn commit
- C: lock for rewrite, when GC and so on

Since B is append-only, so if A has got the value and set pointer to the region, B should not be blocked after that. Maybe this is an opportunity to use locks with finer granularity?

**Comment by funny-falcon** [comment] 2018-02-20 13:49
I closed #418 as duplicate of this.

**Comment by janardhan1993** [comment] 2018-02-26 11:12
@MoZhonghua  @funny-falcon  Can you please try the lastest master

**Comment by funny-falcon** [comment] 2018-02-26 12:57
@janardhan1993 much better!!! There are small pauses, but it doesn't stall. Therefore for batch job it will work.

**Comment by funny-falcon** [comment] 2018-02-26 12:59
To be honest, pause is not that small: it could be several seconds.

**Comment by janardhan1993** [comment] 2018-02-26 13:04
Can you share your workload, are you doing heavy writes ?

**Comment by funny-falcon** [comment] 2018-02-26 13:08
Simulation of intendent workload were in #418 . Due to bug I switch to insert-only workload.

**Comment by manishrjain** [comment] 2018-03-01 02:57
Looking again.

**Closed** 2018-03-01 03:16 UTC
Labels: investigate
