### ISSUE TITLE
many values lost after GC, error Bad Value: data_79335150578 Unable to read from value log

### ISSUE THREAD

**Issue by RyouZhang** [dgraph-io/badger#345] opened 2017-12-10 06:52 UTC
line 923 miss close, it will lock vlogfile
**it := txn.NewIterator(opts)
defer it.Close()**

**Comment by RyouZhang** [comment] 2017-12-10 10:23
another bug, when i do like:
`	db.PurgeOlderVersions()
	for {
		err := db.RunValueLogGC(0.5)
		if err != nil {
			fmt.Println(err)
			break			
		}	
	}`
then many values lost, i get Bad Value: data_79335150578 Unable to read from value log: {Fid:26 Len:6635 Offset:513712869}: Unable to find log file. Please retry

**Comment by janardhan1993** [comment] 2017-12-11 02:05
@RyouZhang: Are you getting bad value error in RunValueLogGC ?

**Comment by RyouZhang** [comment] 2017-12-11 03:09
@janardhan1993 no, RunValueLogGC will delete all vlog file execept the last one

**Comment by janardhan1993** [comment] 2017-12-11 03:37
@RyouZhang: I didn't get what you meant. 
Can you please explain in detail what do you mean when you say many values lost after ValugeLogGC. 
Did you have any open transactions from before calling PurgeOlderVersions

**Comment by RyouZhang** [comment] 2017-12-11 06:19
Yes, i have many transactions before calling PurgeOlderVersions, but the PurgeOlderVersions only mark the old item to delete, the open transactions will not affect this。
the read can't changed item version, the write will add item version

in the case, the old vlog must have some valid item, but not rewrite to new vlog

**Comment by janardhan1993** [comment] 2017-12-11 07:27
As you can see in our godocs, read transactions started prior to calling purgeolderversions shouldn't be used later.
` // This function could be called prior to doing garbage collection to clean up
   3 // older versions that are no longer needed. The caller must make sure that
   4 // there are no long-running read transactions running before this function is
   5 // called, otherwise they will not work as expected.
`
AFAIK PurgeOlderVersions removes the underlying value log file, so the file can get deleted between calling txn.Get and item.value. We don't do reference counting fro value log file during Gets. If you use an iterator then then underlying value log file won't be deleted.

@manishrjain , @deepakjois might have better idea about this.

**Comment by RyouZhang** [comment] 2017-12-11 08:08
my case is very special
20 min, I will write 20w pairs to badger include 19w update 1w insert
after these, call  
`db.PurgeOlderVersions() for { err := db.RunValueLogGC(0.5) if err != nil { fmt.Println(err) break } }`
then check all keys and values

**Comment by RyouZhang** [comment] 2017-12-11 11:24
ok, maybe i find the reason.
many key delete by this code, in value.go
`func discardEntry(e Entry, vs y.ValueStruct) bool {
	if vs.Version != y.ParseTs(e.Key) {
		// Version not found. Discard.		
		return true
	}
`
the vs.Version is different, like this
6049 [104 105 115 116 111 114 121 95 97 100 95 55 56 49 54 54 55 54 50 56 49 55 255 255 255 255 255 255 220 123] 9092

**Comment by RyouZhang** [comment] 2017-12-11 11:46
ask a question about ValueStrcut.Version
why the Version can save?? but in value.go
`
	if vs.Version != y.ParseTs(e.Key) {
		// Version not found. Discard.	
		return true
	}
`

**Comment by janardhan1993** [comment] 2017-12-12 00:03
@RyouZhang: can you please share an working example so that we can reproduce the issue you are facing.
vs.Version != y.ParseTs(e.Key), If lsm gets compacted than the key with that version might be gone so we check if the key with the same version is present in lsm or not before deciding it to discard from value log. (Our internal get function seeks for a key with <= given version => this is not exposed to the user).

**Comment by RyouZhang** [comment] 2017-12-14 07:54
ok, this is my test code
[
[storage.zip](https://github.com/dgraph-io/badger/files/1558297/storage.zip)
](url)

**Comment by janardhan1993** [comment] 2017-12-14 10:20
@RyouZhang Value log is WAL in badger so until memtables are flushed and written to .sst files the corresponding value log files won't be eligible for GC. Memtable is flushed only when it reaches around 64 mb, since the memtable would have only the key and pointer to the value if you write 10^6 key value pairs(with value size 100k), memtable would consume only around 20mb(assuming 20bytes per key value pair) whereas value log  can be in GBs.

**Comment by RyouZhang** [comment] 2017-12-14 10:30
@janardhan1993 so this sample write 1000k pairs

**Comment by janardhan1993** [comment] 2017-12-14 10:54
@RyouZhang: Thanks for sharing your code, Will update once we fix the issue.

**Comment by RyouZhang** [comment] 2017-12-15 07:36
@janardhan1993 
in discardEntry, I add this code:
```

if string(e.Key[:len(e.Key)-8]) == "bucket_1000" {
	fmt.Println("discardEntry:", vs.Version, y.ParseTs(e.Key), vs.Meta)
}

```
before call GC
key: bucket_1000
item.Vwersion(): 4060

Start RunValueLogGC
logs:
discardEntry: 20 20 1
discardEntry: 20 20 1
discardEntry: 2057 2057 1
discardEntry: 20 20 1
discardEntry: 2057 4060 1

**Comment by janardhan1993** [comment] 2017-12-15 07:49
@RyouZhang : Please try with latest code, it's fixed now.

**Comment by RyouZhang** [comment] 2017-12-15 08:57
@janardhan1993 better than before, but aways loss some keys

**Comment by janardhan1993** [comment] 2017-12-18 01:57
@RyouZhang : Can you please try again on master.

**Comment by RyouZhang** [comment] 2017-12-18 02:37
@janardhan1993 thanks for your work, now it works fine.

**Closed** 2017-12-18 02:40 UTC
Labels: bug
