### ISSUE TITLE
[BUG]: panic happened in badger on restart after the laptop pc is power off since of no power. 

### ISSUE THREAD

**Issue by sureone** [dgraph-io/badger#1846] opened 2023-01-16 02:23 UTC
### What version of Badger are you using?

github.com/dgraph-io/badger/v3 v3.2103.4

### What version of Go are you using?

1.18

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

RAM: 32GB 
CPU: Intel i5
OS: Windows 10

### What steps will reproduce the bug?

power off the laptop
restart the programe

### Expected behavior and actual result.

should read the db correctly.

### Additional information

Exception has occurred: panic
"\n== Recovering from initIndex crash ==\nFile Info: [ID: 2, Size: 43...
Stack:
	 2  0x0000000001853dcc in github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest.func1.1
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:351
	 4  0x0000000001853525 in github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest.func1
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:397
	 7  0x00000000018374ef in github.com/google/flatbuffers/go.GetInt32
	     at go/pkg/mod/github.com/google/flatbuffers@v1.12.1/go/encode.go:85
	 8  0x000000000183783f in github.com/google/flatbuffers/go.GetUOffsetT
	     at go/pkg/mod/github.com/google/flatbuffers@v1.12.1/go/encode.go:121
	 9  0x000000000183c0b2 in github.com/dgraph-io/badger/v3/fb.GetRootAsTableIndex
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/fb/TableIndex.go:14
	10  0x0000000001856a6d in github.com/dgraph-io/badger/v3/table.(*Table).readTableIndex
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:707
	11  0x00000000018544fc in github.com/dgraph-io/badger/v3/table.(*Table).initIndex
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:462
	12  0x0000000001852f2c in github.com/dgraph-io/badger/v3/table.(*Table).initBiggestAndSmallest
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:401
	13  0x0000000001852910 in github.com/dgraph-io/badger/v3/table.OpenTable
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/table/table.go:308
	14  0x0000000001895ea5 in github.com/dgraph-io/badger/v3.newLevelsController.func1
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/levels.go:150
	15  0x00000000018959f1 in github.com/dgraph-io/badger/v3.newLevelsController.func3
	     at go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.4/levels.go:165

**Comment by mangalaman93** [comment] 2023-03-18 08:08
This seems like a duplicate of #1883

**Closed by mangalaman93** 2023-03-18 08:08 UTC
Labels: kind/bug
