### ISSUE TITLE
Crash because of unsafe pointer usage in AndreasBriese/bbloom library

### ISSUE THREAD

**Issue by jmozah** [dgraph-io/badger#1294] opened 2020-04-09 15:19 UTC
fatal error: checkptr: unsafe pointer arithmetic

goroutine 16 [running]:
runtime.throw(0xe12690, 0x23)
	/opt/hostedtoolcache/go/1.14.2/x64/src/runtime/panic.go:1116 +0x72 fp=0xc0000893d0 sp=0xc0000893a0 pc=0x446cd2
runtime.checkptrArithmetic(0xc00022a080, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.2/x64/src/runtime/checkptr.go:43 +0xb5 fp=0xc000089400 sp=0xc0000893d0 pc=0x418115
github.com/AndreasBriese/bbloom.Bloom.JSONMarshal(0x0, 0xe, 0xc00022a080, 0x8, 0x8, 0x9, 0x1ff, 0x7, 0x37, 0x0, ...)
	/home/runner/go/pkg/mod/github.com/!andreas!briese/bbloom@v0.0.0-20190306092124-e2d15f34fcf9/bbloom.go:238 +0xd1 fp=0xc0000894e8 sp=0xc000089400 pc=0xa086d1
github.com/dgraph-io/badger/table.(*Builder).Finish(0xc0002028a0, 0xc0002800cb, 0x14, 0x533322e)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/table/builder.go:229 +0x7c1 fp=0xc000089ac8 sp=0xc0000894e8 pc=0xa0b621
github.com/dgraph-io/badger.writeLevel0Table(0xc0001aa060, 0x2a00000000, 0x39, 0x0, 0x0, 0x0, 0xf096a0, 0xc000206018, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:845 +0x618 fp=0xc000089ca0 sp=0xc000089ac8 pc=0xa2a828
github.com/dgraph-io/badger.(*DB).handleFlushTask(0xc0000fd180, 0xc0001aa060, 0x2a00000000, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:884 +0x5af fp=0xc000089e00 sp=0xc000089ca0 pc=0xa2ae8f
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc0000fd180, 0xc00012a0a0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:918 +0x1cc fp=0xc000089f98 sp=0xc000089e00 pc=0xa2b62c
github.com/dgraph-io/badger.Open.func4(0xc000010318)
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:298 +0x8b fp=0xc000089fd8 sp=0xc000089f98 pc=0xa70e2b
runtime.goexit()
	/opt/hostedtoolcache/go/1.14.2/x64/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000089fe0 sp=0xc000089fd8 pc=0x47a871
created by github.com/dgraph-io/badger.Open
	/home/runner/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:297 +0x2308

### What version of Go are you using (`go version`)?
1.14

<pre>
$ go version

</pre>

### What version of Badger are you using?
1.6.0

### Does this issue reproduce with the latest master?
not sure

### What are the hardware specifications of the machine (RAM, OS, Disk)?
github CI

### What did you do?
opened the badger dB

### What did you expect to see?

DB opened and working

### What did you see instead?
a core dump

**Comment by jmozah** [comment] 2020-04-09 16:31
@jarifibrahim checked this in 2.0.3 also... i am getting the same error...
But this only happens in the github CI and not in our local machines..

**Comment by jarifibrahim** [comment] 2020-04-09 16:34
@jmozah Can you please point me to the github build that failed? I'd like to see how badger was built.

**Comment by jmozah** [comment] 2020-04-09 16:36
@jarifibrahim looks like it is passing in 2.0.3. 
for the 1.6 logs .. lok at https://github.com/ethersphere/bee/pull/75/checks?sha=1551a2540b278ff94f8d6060ac1ad08dbfd8edae

**Comment by jarifibrahim** [comment] 2020-04-09 16:51
Related to https://github.com/dgraph-io/badger/issues/1096

**Comment by jarifibrahim** [comment] 2020-04-15 12:38
The issue is because an older version of `AndreasBriese/bbloom` had unsafe pointer handling (https://github.com/AndreasBriese/bbloom/issues/9). It has been fixed and updating the bbloom version in badger should fix this issue.

**Comment by jarifibrahim** [comment] 2020-04-22 05:49
Fixed and merged to `release/v1.6` branch via https://github.com/dgraph-io/badger/pull/1305 .
The next release of 1.6.x version will have this fix.

Thanks for reporting the issue @jmozah

**Closed by jarifibrahim** 2020-04-22 05:49 UTC
Labels: kind/bug, priority/P2, status/accepted, status/more-info-needed
