### ISSUE TITLE
how to recover Invalid value pointer offset

### ISSUE THREAD

**Issue by speakinLzy** [dgraph-io/badger#828] opened 2019-05-27 07:52 UTC
version v2.0.0-rc.2
system windows 7

I don't know how to recover “Invalid value pointer offset: 224487 greater than current offset: 0”

**Comment by ashish-goswami** [comment] 2019-05-27 08:11
@speakinLzy can you help us reproduce this? What operation were you trying when you got this?

**Comment by jarifibrahim** [comment] 2019-05-27 08:18
Duplicate of https://github.com/dgraph-io/badger/issues/434. 
@speakinLzy Can you try running the DB with `Truncate=True` https://github.com/dgraph-io/badger/blob/master/options.go#L63 ? 
This issue was fixed in https://github.com/dgraph-io/badger/commit/deb140b6378159c58f803c01430a1b6ba3af248e

**Comment by speakinLzy** [comment] 2019-05-27 08:19
@ashish-goswami 
I try to reproduce this。。。
now i have [](https://i.loli.net/2019/05/27/5ceb9d6bd9deb38816.png)

**Comment by speakinLzy** [comment] 2019-05-27 08:22
@jarifibrahim 
![image](https://user-images.githubusercontent.com/31429077/58406119-7dc72480-809b-11e9-8c04-215189cdd4f1.png)
not effective。。。

**Comment by speakinLzy** [comment] 2019-05-27 08:25
@ashish-goswami I don't kwon how to happen this now...I try to  reproduce this...

**Comment by jarifibrahim** [comment] 2019-05-27 08:34
@speakinLzy can you share you badger directory? Looks like your badger directory has some corrupted data.

**Comment by speakinLzy** [comment] 2019-05-27 08:36
@jarifibrahim

**Comment by speakinLzy** [comment] 2019-05-27 08:37
@jarifibrahim 
[data.zip](https://github.com/dgraph-io/badger/files/3222590/data.zip)

**Comment by jarifibrahim** [comment] 2019-05-27 09:04
The directory works fine for me on v2.0.0-rc.2 (linux)
```go
	dir := "/tmp/data"
	opts := badger.DefaultOptions
	opts.Dir = dir
	opts.ValueDir = dir
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()
```
```
badger 2019/05/27 14:29:48 INFO: All 1 tables opened in 0s
badger 2019/05/27 14:29:48 INFO: Replaying file id: 0 at offset: 266517
badger 2019/05/27 14:29:48 INFO: Replay took: 25.475µs
badger 2019/05/27 14:29:48 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
```

@speakinLzy Can you confirm you've sent the correct badger directory?

**Comment by speakinLzy** [comment] 2019-05-27 09:10
@jarifibrahim What system are you using?

**Comment by speakinLzy** [comment] 2019-05-27 09:16
@jarifibrahim my mistaken
open is no problem
my error in
![image](https://user-images.githubusercontent.com/31429077/58409701-2f1d8880-80a3-11e9-97a8-b15e48b95fb9.png)
![image](https://user-images.githubusercontent.com/31429077/58409712-347ad300-80a3-11e9-8f79-c6a01ef86d0a.png)

**Comment by jarifibrahim** [comment] 2019-05-27 13:17
@speakinLzy I tried to iterate over all the values in the data directory provided by you and it works for me.

Can you provide me the complete script you're using? Also, can you check if closing the DB isn't returning any errors?

**Comment by speakinLzy** [comment] 2019-05-28 02:57
@jarifibrahim my demo
[test.zip](https://github.com/dgraph-io/badger/files/3225467/test.zip)

**Comment by jarifibrahim** [comment] 2019-05-28 16:25
I was able to reproduce this on version v2.0.0-rc.2 and master.

**Comment by jarifibrahim** [comment] 2019-05-29 11:52
@speakinLzy The log file in your DB directory is completely empty. Do you have any idea how this might have happened? The log file works as a write ahead log for badger. If the value log file itself is empty, there might be something wrong with your code (or system).

One possible explanation for this is that your DB crashed and the log file was corrupted completely (I don't know how this could happen). So when the DB was started the second time (with truncate=true) it truncated all the entries in vlog file but the SST table file still holds pointers to the values. 
Now when we're iterating over the keys, the values are missing because the file no longer contains the data.

**Comment by speakinLzy** [comment] 2019-05-30 02:42
@jarifibrahim I open a db (with truncate=true)，DB directory have a lock file。can i open second time？

**Comment by jarifibrahim** [comment] 2019-05-30 06:21
@speakinLzy The `LOCK` file in badger directory ensures only one process can access badger. If your directory has the `LOCK` file even after closing the DB that means the DB didn't close properly.

As for the reported issue, the error you're seeing is expected. Your vlog file is empty and hence the `item.Value(...)` call is returning an error. This isn't a recoverable error because you've lost data (empty vlog file).

You don't want to kill your process when `item.Value(...)` returns an error. You can handle the error and move to the next item in the iteration.

I'm going to close this issue since it is the expected behavior. Feel free to reopen.

**Closed by jarifibrahim** 2019-05-30 06:21 UTC
Labels: kind/bug, status/accepted, status/more-info-needed
