### ISSUE TITLE
CompactL0OnClose fails on closing db

### ISSUE THREAD

**Issue by abrosimov** [dgraph-io/badger#970] opened 2019-08-07 14:01 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 linux/amd64
</pre>

### What version of Badger are you using?
github.com/dgraph-io/badger v2.0.0-rc2+incompatible

### Does this issue reproduce with the latest master?
Didn't test, but I think yes, see below

### What are the hardware specifications of the machine (RAM, OS, Disk)?
CentOS, 256GB RAM, 2TB SSD Raid

### What did you do?
Opening DB with following settings:
```go
	opts := badger.
		DefaultOptions(conf.BadgerPath).
		WithNumCompactors(2).
		WithLogger(log.StandardLogger()).
		WithNumVersionsToKeep(1).
		WithCompactL0OnClose(true)

	db, err := badger.Open(opts)
```

Closing function looks like this:
```go
	if err := bb.db.Sync(); err != nil {
		log.Errorf("Failed to sync badger db with error: %v", err)
	}

	log.Infof("Closing database")
	if err := bb.db.Close(); err != nil {
		log.Errorf("Failed to close badger db with error: %v", err)
	}
```

### What did you expect to see?
Correct closing of database

### What did you see instead?
```
Aug  7 13:27:13.293635 [WARN]  <18862> LOG Compact FAILED with error: Writes are blocked, possibly due to DropAll or Close
github.com/dgraph-io/badger.init.ializers
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/errors.go:113
runtime.main
	/usr/lib/go-1.12/src/runtime/proc.go:188
runtime.goexit
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337
failed to push discard stats to write channel
github.com/dgraph-io/badger.(*valueLog).flushDiscardStats
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/value.go:1405
github.com/dgraph-io/badger.(*valueLog).updateDiscardStats
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/value.go:1386
github.com/dgraph-io/badger.(*levelsController).compactBuildTables
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:623
github.com/dgraph-io/badger.(*levelsController).runCompactDef
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:764
github.com/dgraph-io/badger.(*levelsController).doCompact
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:833
github.com/dgraph-io/badger.(*DB).close
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:414
github.com/dgraph-io/badger.(*DB).Close.func1
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:351
sync.(*Once).Do
	/usr/lib/go-1.12/src/sync/once.go:44
github.com/dgraph-io/badger.(*DB).Close
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:350
go.badoo.dev/userkv/ukv/db.(*badgerBackend).Stop
	/home/kabrosimov/Work/userkv/ukv/db/badger_backend.go:436
go.badoo.dev/userkv/ukv.(*Storage).mainLoop
	/home/kabrosimov/Work/userkv/ukv/storage.go:247
runtime.goexit
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337
failed to update discard stats
github.com/dgraph-io/badger.(*levelsController).compactBuildTables
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:624
github.com/dgraph-io/badger.(*levelsController).runCompactDef
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:764
github.com/dgraph-io/badger.(*levelsController).doCompact
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/levels.go:833
github.com/dgraph-io/badger.(*DB).close
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:414
github.com/dgraph-io/badger.(*DB).Close.func1
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:351
sync.(*Once).Do
	/usr/lib/go-1.12/src/sync/once.go:44
github.com/dgraph-io/badger.(*DB).Close
	/home/kabrosimov/.go/pkg/mod/github.com/dgraph-io/badger@v2.0.0-rc2+incompatible/db.go:350
go.badoo.dev/userkv/ukv/db.(*badgerBackend).Stop
	/home/kabrosimov/Work/userkv/ukv/db/badger_backend.go:436
go.badoo.dev/userkv/ukv.(*Storage).mainLoop
	/home/kabrosimov/Work/userkv/ukv/storage.go:247
runtime.goexit
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337: {elog:0xc373ce2820 thisLevel:0xc0016f6060 nextLevel:0xc0016f60c0 top:[0xc07cf15d10 0xc2acc84f00 0xc213630f00 0xc229a57860 0xcb6247a4b0 0xc213630780 0xc26c9e7c20] bot:[0xc0d7534960 0xc043470ff0 0xc12d573770] thisRange:{left:[] right:[] inf:true} nextRange:{left:[95 60 68 40 0 0 0 0 58 108 97 107 97 102 107 97 0 0 0 0 0 0 0 0] right:[255 255 255 92 0 0 0 0 58 115 112 111 116 95 100 98 255 255 255 255 255 255 255 255] inf:false} thisSize:0 dropPrefix:[]}
```

It looks like in https://github.com/dgraph-io/badger/blob/e843141e70ca661856f8f3575b5d2ba12af1f996/db.go#L369 we are blocking writes, but while L0 compaction on close, at https://github.com/dgraph-io/badger/blob/e843141e70ca661856f8f3575b5d2ba12af1f996/db.go#L677, we trying to write data, but we can't do it because writes were blocked earlier. 
So, in case if we need to compact data on close we've got an error

**Comment by sch00lb0y** [comment] 2019-08-08 12:03
Hey @abrosimov,
Got the issue, I just need info. So, that I can narrow down the cause. Are you folks using DropAll or DropPrefix?

**Comment by abrosimov** [comment] 2019-08-08 12:53
Hi, @sch00lb0y.
No, we use badger only for putting new keys and reading them. There is no del/drop operations at all. Also, when i call db.Sync in my example there is no reads/writes to db too.
Maybe this chain of calls will help you:
DB.Close() -> db.close() -> 
	1) atomic.StoreInt32(&db.blockWrites, 1)
	2) if db.opt.CompactL0OnClose { run compaction } -> db.lc.doCompact() -> s.runCompactDef() ->  s.compactBuildTables() -> s.kv.vlog.updateDiscardStats() -> vlog.flushDiscardStats() -> vlog.db.sendToWriteCh() -> if atomic.LoadInt32(&db.blockWrites) == 1 { return nil, ErrBlockedWrites }

**Comment by jarifibrahim** [comment] 2019-09-18 10:10
This issue has been fixed via https://github.com/dgraph-io/badger/pull/976 .

@abrosimov Please try running latest badger.

**Closed by jarifibrahim** 2019-09-18 10:10 UTC
Labels: area/crash, kind/bug, priority/P1, status/accepted
