### ISSUE TITLE
Nil value returned due to movekey version mismatch

### ISSUE THREAD

**Issue by simonxw** [dgraph-io/badger#995] opened 2019-08-20 13:50 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version

</pre>

### What version of Badger are you using?
v1.5.5

### What did you do?

1. keep writing keys 
each round writes 1.5 million keys (768 bytes for key and 1024 for value) and repeatedly update those keys. all in same goroutine

2.  vlog gc every 5 minutes in another goroutine and read keys to verify. 
I can upload test program if needed.

### What did you see instead?
after a while, in my case from 3 hours to 15 hours, I got nil value returned. which is DL issue.

**Comment by simonxw** [comment] 2019-08-20 13:56
After tracing in code. the reason it returns nil value is that the original key has new version v2 in lsm tree. move key only has older version v1, v2 is lost. 

see iterator.go: yieldItemValue
		if vs.Version != item.Version() {
			return nil, nil, nil
		}

**Comment by manishrjain** [comment] 2019-08-20 14:25
@Ibrahim can you look into this?

**Comment by jarifibrahim** [comment] 2019-08-21 05:40
@simonxw Can you share the test program?

**Comment by simonxw** [comment] 2019-08-21 15:50
[main.txt](https://github.com/dgraph-io/badger/files/3526142/main.txt)

**Comment by simonxw** [comment] 2019-08-21 15:51
Just uploaded test code. rename it to .go.

**Comment by jarifibrahim** [comment] 2019-08-22 08:32
@simonxw I ran your program twice. The first time it kept running for 10 hours and then again for 3 hours. I didn't see any nil values. Can you try running the program again and confirm the issue?

**Comment by simonxw** [comment] 2019-08-22 18:39
I ran it 3/4 times and got nil value every time. but from 3 hours to 15 hours. Also which version are you running on? I ran it on 1.5.4 + the patch for #907. 

You may have to run it longer.

**Comment by jarifibrahim** [comment] 2019-08-23 09:19
I tried it on v1.5.5 (as mentioned in the issue). I'll try it once again with 1.5.4.

**Comment by markadev** [comment] 2019-09-03 19:30
Hi, I'm a colleague of @simonxw. I think that we were hitting a bug in 1.5 that was fixed with this commit: https://github.com/dgraph-io/badger/commit/af99e5f9ec18aca5d8ff40d2cfd909f7d21f392d

After upgrading to 1.6.0, I no longer see the nil value problem with this test program any more.

**Comment by jarifibrahim** [comment] 2019-09-18 10:07
Thanks @markadev. Since this issue is no longer reproducible on 1.6.0 I'm going to close this issue.

**Closed by jarifibrahim** 2019-09-18 10:07 UTC
Labels: area/dataloss, priority/P1, status/more-info-needed
