### ISSUE TITLE
Data corruption when not closing on Windows

### ISSUE THREAD

**Issue by zippoxer** [dgraph-io/badger#476] opened 2018-05-06 19:54 UTC
https://github.com/dgraph-io/badger/pull/470 describes and fixes a lock file issue on Windows. The author also describes a data corruption problem on Windows. I can reproduce this problem as well. Quite easily.

On my 64-bit Windows 10 machine, to simulate a crash (opening Badger and not closing it), I ran the following program three times:

```go
import (
	"fmt"
	"github.com/dgraph-io/badger"
)

func main() {
	opts := badger.DefaultOptions
	opts.Dir = "crashtest"
	opts.ValueDir = "crashtest"
	_, err := badger.Open(opts)
	if err != nil {
		fmt.Println(err)
	}
}
```

The first time I ran it, it terminated gracefully. The second run, Badger said there's a lock file, so I removed it and ran the program again. The third time, Badger told me it's corrupted:

```
Unable to replay value log: "crashtest\\000000.vlog": Data corruption detected.
Value log truncate required to run DB. This would result in data loss.
```

This shouldn't happen. I'm using the default options, and badger's writes should be crash-safe.

**Comment by zippoxer** [comment] 2018-05-06 20:30
The value log is actually 2,147,483,648 bytes long.

**Comment by djdv** [comment] 2018-05-09 15:55
@manishrjain 
I'm free to run tests on Windows machines if you need them. Ping me anytime.

**Comment by manishrjain** [comment] 2018-05-09 17:25
Hey @djdv , could you see if you can replicate this bug, and suggest/test solutions?

**Comment by djdv** [comment] 2018-05-09 17:33
The case above is the same for me, on the 3rd run I get
>Unable to replay value log: "crashtest\\000000.vlog": Data corruption detected. Value log truncate required to run DB. This would result in data loss.

with a 2,147,483,648 byte vlog.

Unfortunately, I may not be much help on actually debugging the issue at the moment, but can certainly run tests.

**Comment by djdv** [comment] 2018-05-09 20:28
It seems as though something has to be done to handle dynamically sized memory-mapped files on Windows.
Probably by handling shrinking, growing, and migration manually.
I would assume that on vlog size changes, a new mapping would have to be created, the old data moved over, and references to it would have to be updated, as well as removing the old backing file.

Handling this without impacting performance seems like it could be complex.
Maybe there is a better solution, but that is what came to mind right now. Take into account I'm not familiar with badgers internals yet.

**Comment by manishrjain** [comment] 2018-05-11 19:31
Closing the issue. Feel free to reopen if there's an actual data loss.

**Closed by manishrjain** 2018-05-11 19:31 UTC
Labels: help wanted, wontfix

**Comment by schomatis** [comment] 2018-05-13 20:11
@manishrjain How then can the user differentiate if it's truncating because of how Windows works or because there was actually some data loss that resulted in an inconsistent DB?

**Comment by manishrjain** [comment] 2018-05-13 20:55
Hard to tell, honestly. The chance of actually losing confirmed data with sync writes on, is almost nil. Can only happen if the hard drive has issues and is flipping bits.

**Comment by robinchesterman** [comment] 2018-07-25 08:55
I have a similar issue running dgraph on a Windows VM. Anytime the VM is restarted i.e. forces dgraph to stop unexpectedly, I am unable to restart dgraph server. Lock files exist (which can be deleted), but then I get:

` Error while creating badger KV WAL store error: Value log truncate required to run DB. This might result in data loss.`

I don't know about any data loss. What I don't know how to do is actually get dgraph to restart at all.

**Comment by manishrjain** [comment] 2018-07-26 02:43
Hmm... we'll have to set the truncate option in Dgraph. I'll raise a PR.

**Comment by manishrjain** [comment] 2018-07-26 02:49
I've submitted a change, would be part of v1.0.7 release:
https://github.com/dgraph-io/dgraph/commit/6648f14d09e28a67c83af2dbd9c64a28cead06c2

**Comment by AJAviJain** [comment] 2018-09-10 12:39
Where to set truncate option? I am getting an error >>  Unable to find log file. Please retry. so i think might be the error is same, server and zero are getting started but for some queries in ratel browser, giving this error. (using windows)
