### ISSUE TITLE
OOM when writing to badger

### ISSUE THREAD

**Issue by zjshen14** [dgraph-io/badger#772] opened 2019-04-17 22:16 UTC
Code snippet: https://gist.github.com/zjshen14/c572dcc68bd707dab9d182eeb742c508
Error stack: https://gist.github.com/zjshen14/3b503d1cf464a4a52e78901d0fd9bf02
Version: v2.0.0-rc.2 (as well as v1.5.4)

Crashed when the db footprint on disk grew to 55G.

Is it a bug?

And how to tune the option to walk around?

**Comment by zjshen14** [comment] 2019-04-17 22:18
Is it related to https://github.com/dgraph-io/badger/issues/767?

**Comment by jarifibrahim** [comment] 2019-04-19 15:37
@zjshen14 I ran your script for more than 2 hours and it didn't crash for me. In my case, the db footprint was about 100G
```
$du -lh data1 data2
43G   data1
63G     data2
```


>And how to tune the option to walk around?

There a couple of things you could try. See https://github.com/dgraph-io/badger#memory-usage

How much ram does your system have?

**Comment by jarifibrahim** [comment] 2019-04-19 16:13
>Is it related to #767?

I don't so. #767 seems like a different issue to me.

**Comment by zjshen14** [comment] 2019-04-19 16:34
@jarifibrahim 

I'm using c5.xlarge, which has 8GB mem. and I have a 100G disk with 300 IOPS provisioned. I could quite consistently hit OOM, though the disk size was different when the process got crashed.

> There a couple of things you could try. See https://github.com/dgraph-io/badger#memory-usage

Will take a look

**Comment by zjshen14** [comment] 2019-04-20 01:05
I used  FileIO option: https://gist.github.com/zjshen14/d6537c94c486006bb2a14635a1484234

It will still crash, but silently.

**Comment by jarifibrahim** [comment] 2019-04-25 10:18
@zjshen14 We store [bloomfilters](https://github.com/dgraph-io/badger/blob/master/table/table.go#L71) in the memory. You should get about 1 GB of memory usage with 500 SST tables and 500 SST tables is lot of data. The script you have shared keeps on inserting data infinitely and that's why the size of bloomfilter keeps on increasing. I ran the script for 1.5 hours and I had about 1 GB of bloomfilter (which is expected).

**Comment by zjshen14** [comment] 2019-04-29 17:47
> I ran the script for 1.5 hours and I had about 1 GB of bloomfilter (which is expected).

I have a machine with 16GB mem, and in my last test (see the option above), it crashed without showing OOM. Probably it was caused by something else.

And one step back, in terms of OOM, IMHO, it's way better to slow down the writes (such as swapping the in mem stuff into disk) instead of panic the process with OOM. We intentionally did the stress tested, and the script shared before is kind of the abstraction of the test. We need to make the server still survive under the extreme workload.

**Comment by thumbsized** [comment] 2019-05-12 09:29
Maybe https://github.com/dgraph-io/badger#garbage-collection
Specifically, since yo uare constantly setting the same keys:
`Concurrent read/write transactions could leave behind multiple values for a single key, because they are stored with different versions. These could accumulate, and take up unneeded space beyond the time these older versions are needed.`

and
`Badger relies on the client to perform garbage collection at a time of their choosing. It provides the following method, which can be invoked at an appropriate time:`

**Comment by jarifibrahim** [comment] 2019-05-14 07:55
@thumbsized
>Specifically, since you are constantly setting the same keys:

Not really, if you look closely at https://gist.github.com/zjshen14/c572dcc68bd707dab9d182eeb742c508, we're always inserting a different key

Also, https://github.com/dgraph-io/badger#garbage-collection affects only value log files.
Here's how it works
1. We perform compactions (merge table from one level with another)
2. Remove keys which are no longer valid (deleted or old version keys)

Once these keys are removed from the LSM tree then Garbage Collector can remove these values from the `vlog` file.

The vlog file isn't stored in memory by default so it wouldn't affect the memory consumption.
The issue @zjshen14 initally reported was because of huge size of `bloom filter`. The bloom filter is stored in the memory for faster lookups.

**Comment by jarifibrahim** [comment] 2019-05-14 07:57
>And one step back, in terms of OOM, IMHO, it's way better to slow down the writes (such as swapping the in mem stuff into disk) instead of panic the process with OOM. We intentionally did the stress tested, and the script shared before is kind of the abstraction of the test. We need to make the server still survive under the extreme workload.


@zjshen14 Agreed, we plan on adding limitations on the memory consumption. It's in our roadmap.

**Comment by campoy** [comment] 2019-05-28 23:21
Any updates on this issue, @jarifibrahim?

Have we been able to reproduce it?

**Comment by jarifibrahim** [comment] 2019-06-17 17:24
@campoy Yes, we were able to reproduce the issue.
We store `bloom filters` in memory for each table. If there are too many tables, the `bloom filters` will consume too much of memory and badger will crash with a `OOM` error. We gave some thought to it and decided that we can limit the memory usage of bloom filters if we were to have a cache.
We would need a cache any way when we support compression and encryption.

**Comment by manishrjain** [comment] 2019-07-17 17:40
Should we mark it as accepted, considering @ashish-goswami is working on a change to allow people to limit the bloom filter memory usage.

**Comment by jarifibrahim** [comment] 2019-07-18 05:15
Assigned to @ashish-goswami.

**Comment by ashish-goswami** [comment] 2019-08-01 23:01
PR https://github.com/dgraph-io/badger/pull/940 adds an option to DB, BloomFalsePositive. Lower the value of BloomFalsePositive higher is the memory used by Blooms. Hence to minimise memory usage, BloomFalsePositve can be set to a large value.

**Comment by ashish-goswami** [comment] 2019-08-01 23:15
Closing this for now. Feel free to reopen it if required.

**Closed by ashish-goswami** 2019-08-01 23:15 UTC
Labels: area/crash, kind/bug, priority/P1, status/accepted
