### ISSUE TITLE
RunValueLogGC crashed

### ISSUE THREAD

**Issue by cedricfung** [dgraph-io/badger#1139] opened 2019-11-28 02:24 UTC
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.4 linux/amd64
</pre>

### What version of Badger are you using?
v2.0.0

### Does this issue reproduce with the latest master?
Never tried

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Linux 64 SSD

### What did you do?

```golang
	opts := badger.DefaultOptions(dir)
	opts.SyncWrites = sync
	db, err := badger.Open(opts)
	if err != nil {
		return nil, err
	}
	db.RunValueLogGC(0.1)

	go func() {
		ticker := time.NewTicker(1 * time.Minute)
		defer ticker.Stop()
		for range ticker.C {
			lsm, vlog := db.Size()
			if lsm > 1024*1024*8 || vlog > 1024*1024*32 {
				db.RunValueLogGC(0.5)
			}
		}
	}()
```

### What did you expect to see?
Run value log gc should work

### What did you see instead?

```
mixin[28404]: github.com/dgraph-io/badger/v2/y.AssertTrue
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/y/error.go:55
mixin[28404]: github.com/dgraph-io/badger/v2.(*valueLog).doRunGC.func2
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1591
mixin[28404]: github.com/dgraph-io/badger/v2.(*valueLog).iterate
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:480
mixin[28404]: github.com/dgraph-io/badger/v2.(*valueLog).doRunGC
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1557
mixin[28404]: github.com/dgraph-io/badger/v2.(*valueLog).runGC
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1685
mixin[28404]: github.com/dgraph-io/badger/v2.(*DB).RunValueLogGC
mixin[28404]:         /home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/db.go:1129
mixin[28404]: github.com/MixinNetwork/mixin/storage.openDB.func1
mixin[28404]:         /home/one/github/mixin/storage/badger.go:68
mixin[28404]: runtime.goexit
mixin[28404]:         /snap/go/4762/src/runtime/asm_amd64.s:1357
```

badger.go:68 	db.RunValueLogGC(0.5)

**Comment by jarifibrahim** [comment] 2019-12-06 14:37
Hey @cedricfung , does the issue reproduce after a couple of hours? And do you have more badger logs? The logs you've posted show only the line on which the crash happened but I'd like to understand what the state of badger was when the crash happened. Logs would definitely have some more information.

**Comment by cedricfung** [comment] 2019-12-07 13:33
Hi, I have tried again, it crashes. Our code is https://github.com/MixinNetwork/mixin

```
badger 2019/12/07 13:23:28 INFO: All 105 tables opened in 2.049s
badger 2019/12/07 13:23:28 INFO: Replaying file id: 168 at offset: 215041567
badger 2019/12/07 13:23:30 INFO: Replay took: 1.677080583s
badger 2019/12/07 13:23:30 INFO: Replaying file id: 169 at offset: 0
badger 2019/12/07 13:23:32 DEBUG: Flushing memtable, mt.size=67108931 size of flushChan: 0
badger 2019/12/07 13:23:32 DEBUG: Storing value log head: {Fid:0 Len:0 Offset:0}
badger 2019/12/07 13:23:33 INFO: Replay took: 3.373910494s
badger 2019/12/07 13:23:33 INFO: Replaying file id: 170 at offset: 0
badger 2019/12/07 13:23:35 DEBUG: Flushing memtable, mt.size=67108936 size of flushChan: 0
badger 2019/12/07 13:23:35 DEBUG: Storing value log head: {Fid:0 Len:0 Offset:0}
badger 2019/12/07 13:23:36 INFO: Replay took: 3.082134609s
badger 2019/12/07 13:23:36 INFO: Replaying file id: 171 at offset: 0
badger 2019/12/07 13:23:37 DEBUG: Flushing memtable, mt.size=67108868 size of flushChan: 0
badger 2019/12/07 13:23:37 DEBUG: Storing value log head: {Fid:0 Len:0 Offset:0}
badger 2019/12/07 13:23:39 INFO: Replay took: 2.145432608s
badger 2019/12/07 13:23:39 DEBUG: Value log discard stats empty
badger 2019/12/07 13:23:43 INFO: All 0 tables opened in 0s
badger 2019/12/07 13:23:43 INFO: Replaying file id: 0 at offset: 0
badger 2019/12/07 13:23:44 INFO: Replay took: 917.803776ms
badger 2019/12/07 13:23:44 DEBUG: Value log discard stats empty
badger 2019/12/07 13:23:44 INFO: All 1 tables opened in 1ms
badger 2019/12/07 13:23:44 INFO: Replaying file id: 0 at offset: 82
badger 2019/12/07 13:23:44 INFO: Replay took: 2.879µs
badger 2019/12/07 13:23:44 DEBUG: Value log discard stats empty


2019/12/07 13:30:44 Assert failed
github.com/dgraph-io/badger/v2/y.AssertTrue
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/y/error.go:55
github.com/dgraph-io/badger/v2.(*valueLog).doRunGC.func2
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1591
github.com/dgraph-io/badger/v2.(*valueLog).iterate
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:480
github.com/dgraph-io/badger/v2.(*valueLog).doRunGC
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1557
github.com/dgraph-io/badger/v2.(*valueLog).runGC
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/value.go:1685
github.com/dgraph-io/badger/v2.(*DB).RunValueLogGC
	/home/one/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.0/db.go:1129
github.com/MixinNetwork/mixin/storage.openDB.func1
	/home/one/github/mixin/storage/badger.go:68
runtime.goexit
	/snap/go/4901/src/runtime/asm_amd64.s:1357
```

Above is the full log

**Comment by jarifibrahim** [comment] 2019-12-09 08:00
@cedricfung are you inserting `nil` values? Something like `txn.Set("key", nil)`

**Comment by cedricfung** [comment] 2019-12-09 12:36
I have checked my code and find no nil inserting, only txn.Set("key",
[]byte{})

**Comment by jarifibrahim** [comment] 2019-12-09 12:49
The `txn.Set("key", []byte{})` seems to be causing the issue. We have a check which ensures value length is greater than zero. That check seems to be causing the failure.

**Comment by jarifibrahim** [comment] 2019-12-09 13:09
Hey @cedricfung, just out of curiosity, why are you inserting empty values? What are you trying to accomplish with key-only badger?

**Comment by cedricfung** [comment] 2019-12-10 02:13
Hi @jarifibrahim, I want to maintain many states to indicate that we have those keys set. So they are actually some bool values. I have thought those key only writes and reads would be faster with badger.

**Comment by jarifibrahim** [comment] 2019-12-10 07:54
@cedricfung how can I run https://github.com/MixinNetwork/mixin and reproduce the issue?

**Comment by cedricfung** [comment] 2019-12-10 10:03
1. git clone https://github.com/MixinNetwork/mixin
2. git checkout fd33f483f7b5d0
3. mkdir ~/mixin-data
4. cp config/genesis.json config/nodes.json ~/mixin-data
5. cp config/config.example.json ~/mixin-data
5. go build
6. ./mixin kernel -dir ~/mixin-data -port 7239
7. Ctrl+C to stop the process
8. rm -rf ~/mixin-data/snapshots
8. Get the data http://35.188.235.212/snapshots.tar
9. tar xvf snapshots.tar
10. mv snapshots ~/mixin-data
11. ./mixin kernel -dir ~/mixin-data -port 7239

Ignore other connection logs and wating for about 10 minutes, it should crash.

**Comment by jarifibrahim** [comment] 2019-12-16 13:47
@cedricfung Is there any way I can reproduce this without using your `snapshot` directory? The issue is visible on your directory but I'm trying to figure out how did such an entry (which has `bitvaluepointer` set and has zero length) was inserted into badger.

**Comment by cedricfung** [comment] 2019-12-17 14:39
I don't know yet. Which entry is that?

**Comment by jarifibrahim** [comment] 2019-12-17 15:50
Sorry, I wasn't clear. My question is does the issue show up every time you run your `mixin` project? There is an invalid entry in your badger directory and I'm trying to figure out how was that entry inserted.

**Comment by cedricfung** [comment] 2019-12-18 09:19
It only produces the error on that snapshots data, for a fresh start it won't occur.

**Comment by cedricfung** [comment] 2019-12-18 10:49
Forgot to mention that the snapshots directory is converted from an old version. I upgraded badger from an 2.0-rc version to the latest 2.0 version, following the guide of upgrade from v1.6 to v2.0

**Comment by jarifibrahim** [comment] 2019-12-25 06:46
Ah! Maybe backup is doing something mischievous. I'll look into the backup code and get back to you.

**Comment by cedricfung** [comment] 2020-01-02 02:24
Any updates on this? How could we enable RunValueLogGC again?

**Comment by jarifibrahim** [comment] 2020-01-06 09:20
@cedricfung Unfortunately, I haven't been able to find a test to produce this. I can, however, write a patch for you which will drop the key which seems to be crashing badger. You can run badger with that patch and GC should work fine.

NOTE - You might lose data. I think you just have one key which has the wrong bits set and we'll have to drop it.

Do you think this would unblock you for now?

**Comment by cedricfung** [comment] 2020-01-06 09:35
Which key is that? I'm sure that we have many keys with empty values, because we have code like `err = txn.Set(key, []byte{})`

**Comment by jarifibrahim** [comment] 2020-01-15 08:41
Hey @cedricfung, I haven't been able to find the root cause for this issue but you can use the following diff to clean up the invalid bit set. Here's how you can use it
(Please make a copy of your original data before you run the following commands. I've tested them but in case something goes wrong, we'll still have the original data)

1. Fetch badger and make sure you have the latest master
2. `git apply diff.patch` 
3. Run `go build`/ `go install` 
4. Run `./badger backup --dir /path/to/your/snapshot/directory`
5. Run `./badger restore --dir /path/to/a/new/directory backup.bak`

We created a backup that removed the `bitValuePointer` for the invalid entries and we restored the backup. So now the new data does not have any invalid entries.

(The patch also disables compression. This would reduce the time taken to `restore` the backup)
```diff
diff --git a/backup.go b/backup.go
index aa03339..ebab32f 100644
--- a/backup.go
+++ b/backup.go
@@ -59,14 +59,20 @@ func (stream *Stream) Backup(w io.Writer, since uint64) (uint64, error) {
 			}
 
 			var valCopy []byte
+			// No need to copy value, if item is deleted or expired.
 			if !item.IsDeletedOrExpired() {
-				// No need to copy value, if item is deleted or expired.
-				var err error
-				valCopy, err = item.ValueCopy(nil)
-				if err != nil {
-					stream.db.opt.Errorf("Key [%x, %d]. Error while fetching value [%v]\n",
-						item.Key(), item.Version(), err)
-					return nil, err
+				if item.meta&bitValuePointer > 0 && len(item.val) == 0 {
+					// This entry has wrong bit set. Unset the `bitValuePoiter` bit.
+					item.meta = item.meta &^ (bitValuePointer)
+				} else {
+					// This is a valid entry. Copy its value.
+					var err error
+					valCopy, err = item.ValueCopy(nil)
+					if err != nil {
+						stream.db.opt.Errorf("Key [%x, %d]. Error while fetching value [%v]\n",
+							item.Key(), item.Version(), err)
+						return nil, err
+					}
 				}
 			}
 
diff --git a/options.go b/options.go
index 4374fc3..0bb9699 100644
--- a/options.go
+++ b/options.go
@@ -107,6 +107,9 @@ func DefaultOptions(path string) Options {
 	if !y.CgoEnabled {
 		defaultCompression = options.Snappy
 	}
+
+	defaultCompression = options.None
+
 	return Options{
 		Dir:                 path,
 		ValueDir:            path,
```

I ran the same patch on the data directory provided by @cedricfung and all the invalid entries were fixed.

**Comment by jarifibrahim** [comment] 2020-01-15 08:42
Closing this issue since it is not reproducible. The invalid entries might have been added somehow in the older version of badger (I guess).

Please re-open this issue if it shows up again.

**Comment by cedricfung** [comment] 2020-01-20 02:47
Hi @jarifibrahim will this process remove any entries? We need to keep all entries, even empty entries.

**Comment by jarifibrahim** [comment] 2020-01-20 08:19
@cedricfung No. It would not. The code above would take a backup of your current badger directory and unset the bit which was causing the issue. We're reinserting all the entries when you restore that backup. 

The process should not cause any data to be lost since your values are `nil`. However, please make a copy of your existing data. It might help if something goes wrong :)

**Comment by cedricfung** [comment] 2020-01-20 09:50
Thank you. I'm curious about the backup file size, my data is 47GB, and the backup is only 11GB, but the backup of v1.6 is 37GB. Is this normal?

**Comment by cedricfung** [comment] 2020-01-20 09:54
After I restored the data, the directory is only 20GB. And my program can't start with this new data set.

**Comment by jarifibrahim** [comment] 2020-01-20 10:16
>Thank you. I'm curious about the backup file size, my data is 47GB, and the backup is only 11GB, but the backup of v1.6 is 37GB. Is this normal?

The size reduction is expected because backup uses protobuf to store data which is supposed to reduce the disk space.

>but the backup of v1.6 is 37GB.

There shouldn't be such a huge size difference between v1.6.0 and v2.0.0
How did you take the backup? The directory you've shared in https://github.com/dgraph-io/badger/issues/1139#issuecomment-563959632 wouldn't work with badger v1.6.

>After I restored the data, the directory is only 20GB. And my program can't start with this new data set.

Are you able to open badger directory? Can you show me some logs?

**Comment by cedricfung** [comment] 2020-01-20 10:33
> How did you take the backup? The directory you've shared in #1139 (comment) wouldn't work with badger v1.6.

I have kept the old backup from v1.6, so I compared the size.

I tried the steps again and get the same error. The database opened, but I think some value lost. The error is:

```
	copy(publicSpend[:], ival[:len(publicSpend)])
panic: runtime error: slice bounds out of range [:32] with capacity 0
```

So it means the ival has zero length, it should have at least 32 bytes.

**Comment by jarifibrahim** [comment] 2020-01-20 10:48
> I tried the steps again and get the same error. The database opened, but I think some value lost. The error is:
> 
> ```
> 	copy(publicSpend[:], ival[:len(publicSpend)])
> panic: runtime error: slice bounds out of range [:32] with capacity 0
> ```
> 
> So it means the ival has zero length, it should have at least 32 bytes.

Was this value read from badger? If badger has zero-length values, why does this code need 32 bytes?

**Comment by cedricfung** [comment] 2020-01-20 10:59
This value read from badger. This value should have 64 bytes before those steps. It has 64 bytes in the original dataset.

**Comment by jarifibrahim** [comment] 2020-01-21 09:37
@cedricfung Can you check the length of the `value` returned by badger? If badger is returning an empty value, your code should work fine. Is that right?

**Comment by cedricfung** [comment] 2020-01-21 12:00
I'm inserting []byte{} entries, but it is not this entry. I'm sure that this entry should have at least 32 bytes value. This exact entry is not empty.

**Comment by cedricfung** [comment] 2020-02-05 09:52
Hi @jarifibrahim any updates on this?

**Comment by jarifibrahim** [comment] 2020-02-07 09:57
Hey @cedricfung , sorry it took me so long to reply.
Can you help me understand what do you mean by 
```
I'm inserting []byte{} entries, but it is not this entry. I'm sure that this entry should have at least 32 bytes value. This exact entry is not empty.
```

Initially, I understood that you're inserting zero-length values in badger, but I guess that's not the case.
Are you saying that you inserted `32 bytes` long values and received `zero-length` values back?
I tried to look at the code of https://github.com/MixinNetwork/mixin to figure out what's going on but lost my way around the codebase.

**Comment by cedricfung** [comment] 2020-02-07 12:53
Hi, badger works very well. It's your modified patch that doesn't work. The
patch backup our data, and lost some data. Because I'm sure that the
original data has more than 32 bytes for that key, but the data restored
from your patch is zero length or just lost.

**Comment by jarifibrahim** [comment] 2020-02-10 14:40
Hey @cedricfung, I ran the following patch (I made one small change so that we don't delete any key. We'll keep even the deleted/discard ones on restore) on the `snapshots.tar` you had sent.
I can confirm the number of keys in the snapshots directory before clean up and after clean up is the same.

In your snapshots directory
```
 ~/mixin-data/snapshots  ll -S | head                                       
total 42G
-rw------- 1 ibrahim ibrahim 1.1G Feb 10 19:14 000167.vlog
-rw------- 1 ibrahim ibrahim 914M Feb 10 19:16 000166.vlog
-rw------- 1 ibrahim ibrahim 717M Feb 10 19:15 000163.vlog
-rw------- 1 ibrahim ibrahim 606M Feb 10 19:16 000162.vlog
-rw------- 1 ibrahim ibrahim 515M Feb 10 19:15 000161.vlog
-rw------- 1 ibrahim ibrahim 445M Feb 10 19:15 000098.vlog
-rw------- 1 ibrahim ibrahim 435M Feb 10 19:13 000164.vlog
-rw------- 1 ibrahim ibrahim 408M Feb 10 19:16 000153.vlog
-rw------- 1 ibrahim ibrahim 407M Feb 10 19:16 000074.vlog

```
 - Total Number of keys: 177,148,831
 - Total Number of Unique Keys: 153, 839, 227
 - Total Number of Invalid keys: 12, 797, 570

In the badger directory generated after backup-restore
```
~/mixin-data/snapshots-new  ll -S | head
total 19G
-rw------- 1 ibrahim ibrahim  70M Feb 10 19:39 001234.sst
-rw------- 1 ibrahim ibrahim  70M Feb 10 19:39 001228.sst
-rw------- 1 ibrahim ibrahim  70M Feb 10 19:39 001232.sst
-rw------- 1 ibrahim ibrahim  70M Feb 10 19:39 001230.sst
-rw------- 1 ibrahim ibrahim  69M Feb 10 19:33 000014.vlog
-rw------- 1 ibrahim ibrahim  69M Feb 10 19:37 001033.sst
-rw------- 1 ibrahim ibrahim  69M Feb 10 19:37 001072.sst
-rw------- 1 ibrahim ibrahim  69M Feb 10 19:37 001069.sst
-rw------- 1 ibrahim ibrahim  69M Feb 10 19:37 001075.sst

```
 - Total Number of keys: 177,148,831
 - Total Number of Unique Keys: 153, 839, 227
 - Total Number of Invalid keys: 0

I am not sure why the directory sizes defer by so much but as long as all the keys are present in the new badger directory, we should be fine.

Please try out this patch and let me know how it goes
```diff
diff --git a/backup.go b/backup.go
index aa03339..97b469c 100644
--- a/backup.go
+++ b/backup.go
@@ -59,14 +59,18 @@ func (stream *Stream) Backup(w io.Writer, since uint64) (uint64, error) {
 			}
 
 			var valCopy []byte
+			// No need to copy value, if item is deleted or expired.
 			if !item.IsDeletedOrExpired() {
-				// No need to copy value, if item is deleted or expired.
-				var err error
-				valCopy, err = item.ValueCopy(nil)
-				if err != nil {
-					stream.db.opt.Errorf("Key [%x, %d]. Error while fetching value [%v]\n",
-						item.Key(), item.Version(), err)
-					return nil, err
+				if item.meta&bitValuePointer > 0 && len(item.val) == 0 {
+					item.meta = item.meta &^ (bitValuePointer)
+				} else {
+					var err error
+					valCopy, err = item.ValueCopy(nil)
+					if err != nil {
+						stream.db.opt.Errorf("Key [%x, %d]. Error while fetching value [%v]\n",
+							item.Key(), item.Version(), err)
+						return nil, err
+					}
 				}
 			}
 
diff --git a/badger/cmd/backup.go b/badger/cmd/backup.go
index 79fa9fd..189c296 100644
--- a/badger/cmd/backup.go
+++ b/badger/cmd/backup.go
@@ -18,6 +18,7 @@ package cmd
 
 import (
 	"bufio"
+	"math"
 	"os"
 
 	"github.com/dgraph-io/badger/v2"
@@ -53,7 +54,8 @@ func doBackup(cmd *cobra.Command, args []string) error {
 	// Open DB
 	db, err := badger.Open(badger.DefaultOptions(sstDir).
 		WithValueDir(vlogDir).
-		WithTruncate(truncate))
+		WithTruncate(truncate).WithNumVersionsToKeep(math.MaxUint32))
+
 	if err != nil {
 		return err
 	}
diff --git a/badger/cmd/restore.go b/badger/cmd/restore.go
index d5ee8f5..ee074f3 100644
--- a/badger/cmd/restore.go
+++ b/badger/cmd/restore.go
@@ -18,6 +18,7 @@ package cmd
 
 import (
 	"errors"
+	"math"
 	"os"
 	"path"
 
@@ -65,7 +66,8 @@ func doRestore(cmd *cobra.Command, args []string) error {
 	}
 
 	// Open DB
-	db, err := badger.Open(badger.DefaultOptions(sstDir).WithValueDir(vlogDir))
+	db, err := badger.Open(badger.DefaultOptions(sstDir).
+		WithValueDir(vlogDir).WithNumVersionsToKeep(math.MaxUint32))
 	if err != nil {
 		return err
 	}
```

**Comment by jarifibrahim** [comment] 2020-02-10 14:43
You can use this test to count the number of keys (put it anywhere in the badger directory)
```go
var dir1 string = "/home/ibrahim/mixin-data/snapshots"    
    
func TestDumpKey(t *testing.T) {    
    opt := DefaultOptions(dir1)    
    opt.NumVersionsToKeep = math.MaxUint32    
    //opt.ReadOnly = true    
    
    db, err := Open(opt)       
    require.NoError(t, err)    
    
    txn := db.NewTransaction(false)    
    defer txn.Discard()    
    
    iopt := DefaultIteratorOptions    
    //iopt.AllVersions = true    // Uncomment this if you want to see all the keys in badger.
    
    it := txn.NewIterator(iopt)    
    defer it.Close()    
    
    var keys, keysWithEmptyValue int    
    for it.Rewind(); it.Valid(); it.Next() {    
        keys++    
        item := it.Item()    
        item.Value(func(val []byte) error {    
            if len(val) == 0 && item.meta&bitValuePointer > 0 {    
                keysWithEmptyValue++    
            }    
            return nil    
        })    
    }    
    fmt.Printf("keys: %d\n Keys with zero length value: %d\n", keys, keysWithEmptyValue)    
}    
```

**Comment by xiusin** [comment] 2020-04-07 08:20
the same 
```
 [ERRO] msg: runtime error: slice bounds out of range [4294967295:6231]  

 stack: goroutine 75 [running]:
runtime/debug.Stack(0x3, 0x7fe5274c1560, 0x0)
        /home/xiusin/.bin/go/src/runtime/debug/stack.go:24 +0x9d
github.com/xiusin/pine.defaultRecoverHandler(0xc01d8c2080)
        /mnt/c/projects/src/github.com/xiusin/pine/error.go:79 +0x34
github.com/xiusin/pine.(*Context).endRequest(0xc01d8c2080, 0x116f018)
        /mnt/c/projects/src/github.com/xiusin/pine/context.go:96 +0xf2
panic(0x107ad60, 0xc01d9f5160)
        /home/xiusin/.bin/go/src/runtime/panic.go:967 +0x166
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc0002dedc8, 0x71c00000000, 0xc000002f1e, 0xc01da8d5c0, 0x7fe5274c1560, 0x0, 0xc018580684, 0xc, 0x5332c75, 0x17)
        /mnt/c/projects/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/value.go:1512 +0x604
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc00051fa20, 0xc00051fa20, 0x46e0fb, 0xc01d9f5120, 0x42, 0x0, 0xc018580684)
        /mnt/c/projects/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/iterator.go:170 +0x11d
github.com/dgraph-io/badger/v2.(*Item).Value(0xc00051fa20, 0xc00047a730, 0x0, 0x0)
        /mnt/c/projects/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/iterator.go:105 +0xd6
github.com/xiusin/pine/cache/providers/badger.(*PineBadger).Get.func1(0xc01d8c3200, 0x12d0000, 0xc01d8c3200)
        /mnt/c/projects/src/github.com/xiusin/pine/cache/providers/badger/badger.go:67 +0x112
github.com/dgraph-io/badger/v2.(*DB).View(0xc0002dec00, 0xc00047a7b0, 0x0, 0x0)
        /mnt/c/projects/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.2/txn.go:683 +0x92

```

**Comment by jarifibrahim** [comment] 2020-04-30 11:54
This issue seems related to https://github.com/dgraph-io/badger/pull/1313. The `bitValuePointer` might be incorrectly set because of backup restore.

**Comment by cedricfung** [comment] 2020-04-30 16:33
How could we fix our existing data?

Thank you for these efforts.

**Comment by cedricfung** [comment] 2020-05-11 08:13
Any further steps to fix the existing data? Use the master branch to backup and restore? Any special params to use in the backup and restore?

**Comment by cedricfung** [comment] 2020-05-11 12:51
@jarifibrahim yes I'm using the default options.

**Comment by jarifibrahim** [comment] 2020-05-11 13:06
@cedricfung No. If you're using badger with default options, backup and restore on the `latest` master with https://github.com/dgraph-io/badger/pull/1313 should be enough.

**Comment by jarifibrahim** [comment] 2020-06-03 06:42
@cedricfung Are you still seeing crashes? If not, I'd like to mark this issue as fixed and close this issue.

**Comment by cedricfung** [comment] 2020-06-03 11:15
After backup and restore with the master code, no crashes anymore.

**Comment by jarifibrahim** [comment] 2020-06-03 12:12
Perfect. Thank you so much @cedricfung :)

**Closed by jarifibrahim** 2020-06-03 12:12 UTC
Labels: area/crash, kind/maintenance, priority/P1, status/accepted
