### ISSUE TITLE
db.Open returns "unexpected end of JSON input"

### ISSUE THREAD

**Issue by mjentsch** [dgraph-io/badger#830] opened 2019-05-27 14:13 UTC
on 3 of 4 servers. Any idea where this may came from? Databases are ~5TiB.

**Comment by ashish-goswami** [comment] 2019-05-27 14:17
@mjentsch What is the Badger version? Also, tell us the system configuration on which Badger is running.

**Comment by mjentsch** [comment] 2019-05-27 14:26
Current master. Server are CentOS 7 x86_64, Go version is 1.11.5.
What else would be useful to know?

**Comment by ashish-goswami** [comment] 2019-05-27 14:50
I wanted to know about RAM, CPU and disks info. Just to confirm, 5TB is size of single Badger instance?

**Comment by mjentsch** [comment] 2019-05-27 14:58
5TiB is the first of 2 DB dirs and fails to be opened. We have small keys and relative large values.
32G RAM,  8 core, 20TiB filesystem where Badger dirs are located, 4TiB free. Nothing else beside OS and the DB prog running on that box.

**Comment by mjentsch** [comment] 2019-05-27 15:10
Using ./badger info on such DB ends with

[Summary]
Level 0 size:        64 MB
Level 1 size:       252 MB
Level 2 size:       2.6 GB
Level 3 size:       267 MB
Total index size:   3.2 GB
Value log size:     6.1 TB

Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
badger 2019/05/27 15:09:56 INFO: 28 tables out of 51 opened in 3.045s
badger 2019/05/27 15:09:59 INFO: All 51 tables opened in 5.722s
Error: failed to open database: unexpected end of JSON input

**Comment by mjentsch** [comment] 2019-05-27 15:47
I added a line in value.go

        if err := json.Unmarshal(vs.Value, &statsMap); err != nil {
                vlog.opt.Debugf("error unmarshal: %v", statsMap)
                return err
        }

and the compiled badger binary ends with

[Summary]
Level 0 size:        64 MB
Level 1 size:       252 MB
Level 2 size:       2.6 GB
Level 3 size:       267 MB
Total index size:   3.2 GB
Value log size:     6.1 TB

Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
badger 2019/05/27 15:43:11 INFO: 23 tables out of 51 opened in 3.103s
badger 2019/05/27 15:43:14 INFO: 47 tables out of 51 opened in 6.113s
badger 2019/05/27 15:43:14 INFO: All 51 tables opened in 6.333s
badger 2019/05/27 15:43:14 DEBUG: error unmarshal: map[]
Error: failed to open database: unexpected end of JSON input

**Comment by mjentsch** [comment] 2019-05-27 15:55
Added a line to value.go for debugging

        if err := json.Unmarshal(vs.Value, &statsMap); err != nil {
                vlog.opt.Debugf("error unmarshal: %v", string(vs.Value))
                return err
        }

and compiled badger binary ends on problem DB with

[Summary]
Level 0 size:        64 MB
Level 1 size:       252 MB
Level 2 size:       2.6 GB
Level 3 size:       267 MB
Total index size:   3.2 GB
Value log size:     6.1 TB

Abnormalities: None.
0 extra files.
0 missing files.
0 empty files.
0 truncated manifests.
badger 2019/05/27 15:54:31 INFO: 29 tables out of 51 opened in 3.052s
badger 2019/05/27 15:54:34 INFO: All 51 tables opened in 5.616s
badger 2019/05/27 15:54:34 DEBUG: error unmarshal: {"1":37967,"100":15027338,"1007":4616989,"1008":795459,"1009":3005367,"101":65656198,"1013":1708350,"1015":732387,"1017":107815024,"1018":180658655,"1019":168319133,"102":157056912,"1020":54699241,"1021":23381238,"1022":47503484,"1023":46096831,"1024":48319480,"1025":116331410,"1026":77369622,"103":9714399,"104":13960143,"105":20289576,"106":20291847,"107":17916423,"108":26160480,"1081":2502448,"1082":3007334,"1087":1708350,"1088":733676,"1089":1306741,"109":16485684,"1090":7634329,"1091":147334381,"1092":138200625,"1093":177759844,"1094":45010857,"1095":251498477,"1096":45749435,"1097":44953908,"1098":42290590,"1099":65798605,"110":11634316,"1100":144281023,"1101":13102442,"111":52043936,"112":84867114,"113":39682015,"1133":338452,"1138":133016,"1146":21000,"1154":2507460,"1155":1089533,"1156":1930227,"1160":1708350,"1161":734994,"1163":31103514,"1164":176475670,"1165":152007374,"1166":113190932,"1167":45891897,"1168":24982853,"1169":57898598,"1170":38711022,"1171":42643749,"1172":158075695,"1173":32803992,"1184":89955,"1188":2206,"1195":337800,"1201":421449,"1216":30882,"1218":46999,"1227":5518475,"1228":1095930,"1229":1930227,"1233":1708350,"1234":734994,"1236":36041115,"1237":149183603,"1238":184991147,"1239":123692242,"1240":28452316,"1241":42728047,"1242":40224543,"1243":41096416,"1244":43210579,"1245":176587966,"1246":4549554,"1286":128559,"1288":125181,"13":1398529,"1300":2736626,"1301":3029696,"1305":1708580,"1306":1255843,"1307":744741,"1308":1713258,"1309":89703950,"1310":123547032,"1311":207666520,"1312":89086837,"1313":23193972,"1314":43216666,"1315":49882392,"1316":38230200,"1317":67212069,"1318":141671059,"1331":828011,"1345":32742,"1372":2315214,"1373":1141973,"1374":1930227,"1375":778665,"1378":3013202,"1379":748029,"1382":104510544,"1383":108260537,"1384":208730304,"1385":90053808,"1386":25570238,"1387":38215494,"1388":50694887,"1389":37462887,"1390":64780924,"1391":149273522,"1402":47433,"1430":33461,"1446":2328449,"1447":3127207,"1449":780364,"1451":2425019,"1452":1302250,"1453":748029,"1455":74281860,"1456":137892320,"1457":198954840,"1458":101941424,"1459":18813437,"1460":47637806,"1461":40047234,"1462":44922332,"1463":62081676,"1464":150066375,"1465":2561182,"15":34641403,"1518":2337808,"1519":1198030,"1520":1930227,"1521":793627,"1523":718587,"1524":1710296,"1525":2050279,"1528":120105876,"1529":168482590,"1530":138023319,"1531":89656620,"1532":21269793,"1533":52954334,"1534":38787547,"1535":34986793,"1536":122198543,"1537":91388644,"159":75735336,"1592":3244167,"1593":2907642,"1594":3129785,"1596":793799,"1598":2428883,"1599":1302250,"160":125613738,"1600":748029,"1602":40511861,"1603":103575570,"1604":237989258,"1605":126971071,"1606":14417034,"1607":49422191,"1608":44554776,"1609":34372640,"161":28701702,"1610":40182927,"1611":182913712,"162":39873634,"1624":24362,"163":59006530,"164":142514825,"165":3754618,"166":14691648,"1666":2342740,"1667":3036303,"1669":795378,"167":17097889,"1671":2428883,"1672":1302250,"1673":748029,"1675":48079479,"1676":100072998,"1677":268917593,"1678":96924085,"1679":14332249,"168":21950667,"1680":56754423,"1681":36502212,"1682":40162381,"1683":60720650,"1684":156723906,"169":22247838,"170":20199248,"1707":56227493,"171":19188009,"172":54660710,"173":13175556,"174":83283848,"1740":2342740,"1741":3036849,"1743":798969,"1744":718587,"1745":1710296,"1746":2050279,"1749":44939645,"175":51557519,"1750":153535844,"1751":229996251,"1752":83684247,"1753":13251920,"1754":58313732,"1755":42471391,"1756":35994679,"1757":32628639,"1758":184862720,"1785":50617,"1786":50913,"1814":2348195,"1815":3038881,"1817":798969,"1818":718587,"1819":1710296,"1820":5055091,"1823":44943228,"1824":154448490,"1825":229303834,"1826":81188663,"1827":18082428,"1828":57337880,"1829":36258066,"1830":37571142,"1831":35963299,"1832":181534024,"1850":490891,"1886":2707335,"1888":1930227,"1889":814594,"1891":718587,"1892":3013042,"1893":748029,"1895":4436291,"1896":43173436,"1897":154537071,"1898":229442309,"1899":77878637,"190":122264,"1900":19711798,"1901":51697056,"1902":41911647,"1903":35722145,"1904":37952741,"1905":183424356,"1906":157878,"192":121220,"1959":6214735,"1961":1930227,"1962":874222,"1964":718587,"1965":3015149,"1966":748029,"1968":4439280,"1969":57189677,"1970":158104787,"1971":215946916,"1972":82511927,"1973":10063692,"1974":37781605,"1975":47753997,"1976":36254428,"1977":39673974,"1978":187794330,"1979":101532754,"2":31553,"2033":3346285,"2034":1930227,"2036":879105,"2038":2428883,"2039":1304853,"2040":748029,"2042":44682335,"2043":104513147,"2044":205135254,"2045":146687765,"2046":30558302,"2047":30822360,"2048":54733154,"2049":36274761,"2050":29569888,"2051":183581958,"2052":14563662,"2084":132886,"2106":3347797,"2108":1930227,"2109":879105,"2111":718587,"2112":5115559,"2113":748029,"2115":10700595,"2116":131982469,"2117":89177199,"2118":213133555,"2119":70936258,"2120":19120177,"2121":60155599,"2122":43954367,"2123":35157002,"2124":87300033,"2125":117933672,"2180":6327101,"2181":1930227,"2183":880687,"2184":718587,"2185":1710296,"2186":2052882,"2189":56033337,"2190":113318459,"2191":263393182,"2192":66138658,"2193":28479052,"2194":44758456,"2195":49707964,"2196":31433304,"2197":36486582,"2198":189231798,"220":69085212,"221":115368798,"222":19595396,"2225":1117404,"223":24029025,"224":73555075,"225":163621198,"2253":6029804,"2255":1930227,"2256":883612,"2258":718587,"2259":3017015,"226":3431597,"2260":748537,"2262":4443817,"2263":96266045,"2264":48389521,"2265":265769757,"2266":80728222,"2267":17000062,"2268":49484562,"2269":45480269,"227":19376549,"2270":37415247,"2271":56453131,"2272":160275766,"2273":436381,"228":17465667,"2283":21779364,"229":10699751,"230":21672247,"231":12682461,"232":31191821,"2327":3365832,"2329":1931717,"233":53549539,"2330":884275,"2331":718587,"2332":1712897,"2333":2055489,"2336":64955829,"2337":87694407,"2338":213052197,"2339":141026610,"234":20047009,"2340":25535631,"2341":44345154,"2342":46709292,"2343":32004888,"2344":34734058,"2345":191283227,"2346":565552,"235":72793098,"2352":156909,"2355":490437,"236":54202336,"2367":10067502,"237":1659710,"2400":3380158,"2402":2816037,"2404":720813,"2405":3017750,"2406":750636,"2408":4432036,"2409":66562016,"2410":91814428,"2411":254540699,"2412":107389770,"2413":14392427,"2414":43552100,"2415":45386439,"2416":38518488,"2417":32495740,"2418":184214778,"2419":156690,"2430":48019,"2465":60294740,"2473":1673606,"2474":1706887,"2476":2828379,"2478":721183,"2479":3017750,"2480":750636,"2482":5877952,"2483":82790249,"2484":72724840,"2485":256765280,"2486":110513448,"2487":11341248,"2488":45562252,"2489":40694299,"2490":37989796,"2491":28348044,"2492":189119465,"2493":173438,"2496":1405751,"2503":692783,"2546":3380493,"2547":2935932,"2548":1931717,"2549":897200,"2551":721183,"2552":3518280,"2553":750636,"2555":6083577,"2556":82941932,"2557":72757696,"2560":12768313,"2561":48234550,"2562":43352135,"2563":34869692,"2564":54796643,"2565":158843650,"2592":2563383,"2620":3652760,"2622":1931717,"2623":897200,"2625":721183,"2626":4293798,"2627":750923,"2629":13362540,"2630":89730415,"2631":57445454,"2633":107723275,"2634":191703644,"2635":44555136,"2636":24046122,"2637":59481748,"2638":22246211,"2639":186302901,"2640":13216811,"2645":156801,"2650":127013,"266":104188,"2661":840719,"2662":2680809,"2663":8203938,"2664":2527463,"2665":4366633,"2666":18953423,"2667":25967184,"2668":69075309,"2669":70197129,"2670":45247888,"2671":131432648,"2672":70582831,"2673":2722979,"2674":78680929,"2675":82095725,"2676":50561523,"2677":10473702,"2678":27818333,"2679":42036043,"2680":7304381,"2681":1817461,"2682":4840968,"2683":2732369,"2684":32662668,"2685":90233732,"2686":2913242,"2687":4914373,"2688":1901660,"2689":57612137,"2690":57231766,"2691":77811435,"2692":61979070,"2693":40259850,"2694":44901211,"2695":8802159,"2696":19258527,"2697":133732840,"2698":32679728,"2699":22701301,"2700":83615258,"2701":13571456,"2702":167405159,"2703":18554777,"2704":14954525,"2705":227514969,"2706":137867808,"2708":14735624,"2710":4104703,"2711":162355236,"2712":12436886,"2713":24696543,"2714":36600125,"2715":4974001,"2716":30869099,"2717":342546,"2718":13219893,"2719":12962223,"272":31771,"2720":23869535,"2721":64438036,"2722":14022831,"2723":17579124,"2724":5703607,"2726":17130877,"2727":78770953,"2728":1130915,"2729":102908061,"2730":107661944,"2731":93190340,"2732":38077111,"2733":16847921,"2734":13858081,"2735":23172403,"2736":35731920,"2737":33755758,"2738":11836018,"2739":5024751,"2740":79643068,"2741":212756686,"2742":68575034,"2743":43469903,"2744":9235219,"2745":11043649,"2746":18743130,"2747":19940630,"2748":115356876,"2749":29623973,"2750":26250762,"2751":10268333,"2753":33866380,"2754":24004944,"2755":17942881,"2756":131542495,"2757":14258272,"2758":29447404,"2759":397534,"2760":3631640,"2761":16497804,"2762":224194594,"2763":20373249,"2764":55444569,"2765":56422390,"2766":8205618,"2767":38387891,"2768":34307256,"2769":11812911,"2770":43467162,"2771":5992653,"2773":17656038,"2774":239515482,"2775":86051966,"2776":30422742,"2777":330477274,"2778":113550676,"2779":69754765,"2780":76808339,"2781":248529370,"2782":21025174,"2783":6175436,"2784":46981545,"2785":37744264,"2786":121265707,"2787":23397654,"2788":43718769,"2789":44531934,"2790":35286014,"2791":20112781,"2792":72434950,"2793":10611903,"2794":10413109,"2795":602523,"2796":14790869,"2797":12643303,"2798":70847021,"2799":14522649,"2800":18719200,"2801":4383306,"2802":5615345,"2803":14667884,"2804":29154804,"2805":77915718,"2806":16170012,"2807":8223267,"2808":28561148,"2809":19279015,"281":69304279,"2810":72196053,"2811":113223897,"2812":62503831,"2813":58311813,"2814":110365475,"2815":38366787,"2816":20651012,"2817":61387006,"2818":130925043,"2819":67062216,"282":54344382,"2820":48300547,"2821":282649858,"2822":89737848,"2823":63911146,"2824":181426113,"2825":11543450,"2826":40492777,"2827":146568586,"2828":29997486,"2829":154677309,"283":34507236,"2830":10479010,"2831":9513613,"2832":1030002,"2833":16167952,"2834":5788024,"2835":211271516,"2836":39340457,"2837":40911817,"2838":146652511,"2839":7460828,"284":64732856,"2840":1506534,"2841":18994740,"2842":15329705,"2843":138330069,"2844":11509920,"2846":6997666,"2847":24311179,"2848":38403378,"2849":13562569,"285":65554611,"2850":24984776,"2851":82367215,"2852":64178728,"2853":134165157,"2854":18790095,"2855":14836336,"2856":22751411,"2857":84331332,"2858":45749409,"2859":25990100,"286":174172129,"2860":43708638,"2861":5385065,"2862":44621249,"2863":6058624,"2864":63881764,"2866":8056065,"2867":5098293,"2868":12609059,"2869":19486246,"287":6027170,"2870":27284540,"2871":9445431,"2872":375605516,"2873":1875886,"2874":11240307,"2876":42587156,"2877":16132463,"2878":2044659,"2879":11932744,"288":22078100,"2880":26094989,"2881":37117801,"2882":26936120,"2883":32325636,"2884":36007653,"2885":40864932,"2886":79529321,"2887":1763445,"2888":29525885,"2889":27363008,"289":17469492,"2890":88421470,"2891":37201923,"2892":45950210,"2893":35344447,"2894":34233172,"2895":94288250,"2896":55801036,"2897":10763476,"2898":970966,"2899":13749159,"290":1493406,"2900":19619726,"2901":28943325,"2902":9575557,"2903":24006182,"2905":690183,"2906":6341932,"2908":23117402,"2909":6635268,"291":27663451,"2910":14895820,"2911":25291709,"2912":27766414,"2913":61205845,"2914":49218615,"2915":32104626,"2916":4243239,"2917":12622804,"2918":8533481,"2919":94773564,"292":11279107,"2920":91144351,"2921":20685923,"2922":44204857,"2923":23346903,"2924":27576527,"2925":8087536,"2926":120816735,"2927":35242601,"2928":24677238,"293":23569304,"2930":8799926,"2931":21316172,"2932":122600247,"2933":15378270,"2934":5503253,"2935":10942730,"2936":2441034,"2937":5272157,"2938":14186745,"294":16693984,"2940":19885345,"2941":24181788,"2942":31531028,"2943":16956591,"2944":12631102,"2945":13402907,"2946":65293989,"2947":45581209,"2948":107876696,"2949":20748604,"295":58027474,"2950":20903657,"2951":114516633,"2952":336647426,"2953":192795272,"2954":10989113,"2956":28718190,"2957":1869917,"2958":58903437,"2959":18785319,"296":27310450,"2960":2958654,"2961":5803808,"2962":17253705,"2963":62252756,"2964":15802794,"2965":21891734,"2966":51874925,"2967":47044430,"2968":29073458,"2969":40932961,"297":106180345,"2970":22977218,"2971":27929303,"2972":6505322,"2973":40041590,"2974":139291970,"2975":129280777,"2976":378745158,"2977":53956788,"2978":65479378,"2979":16365186,"298":5084582,"2980":80526688,"2981":4544384,"2982":17364665,"2983":19320072,"2984":63147409,"2985":39222521,"2986":20765470,"2987":44073277,"2988":34597479,"2989":23372876,"2990":124904127,"2991":2633773,"2992":16712306,"2993":17693031,"2994":14356806,"2995":31438573,"2996":97881814,"2997":1521646,"2998":20658111,"2999":794391,"3000":3036903,"3001":15562248,"3002":33788961,"3003":18990487,"3004":6335242,"3005":6470444,"3006":40244590,"3007":16420254,"3008":15611509,"3009":11629688,"3010":58334978,"3011":76504934,"3012":3926309,"3013":41344244,"3014":12071812,"3015":16645934,"3016":96318921,"3017":33505128,"3018":17852336,"3019":46367753,"3020":18529424,"3021":39736275,"3022":59200761,"3023":6619009,"3024":20958866,"3025":17538573,"3026":6959025,"3027":46657906,"3028":32851285,"3029":18070784,"3030":23255567,"3031":693420,"3032":11952150,"3033":5404009,"3035":3150774,"3036":22652531,"3037":81340461,"3038":107770642,"3039":73650398,"3040":44977699,"3041":4346875,"3042":7096086,"3043":35459815,"3044":68154667,"3045":2650199,"3046":11838750,"3047":61649757,"3048":83732163,"3049":27008134,"3050":10937210,"3051":50948403,"3052":30531023,"3053":8599492,"3054":5243286,"3055":1974915,"3056":13900700,"3057":32409671,"3058":30263254,"3059":151972618,"3060":14684917,"3061":116375543,"3062":11651012,"3063":62882085,"3064":34110520,"3065":11857379,"3066":94671126,"3067":50525708,"3068":14844943,"3069":8779516,"3070":42219109,"3071":114383954,"3072":66400637,"3073":34622339,"3074":32052583,"3075":3796164,"3076":3967348,"3077":118396312,"3078":72266119,"3079":32357685,"308":2089619,"3080":46729421,"3081":129662197,"3082":17969482,"3083":61139748,"3084":20411200,"3085":23855023,"3086":57678971,"3087":21732930,"3088":108494549,"3089":121081130,"3090":42060281,"3091":14509770,"3092":23922818,"3093":34288209,"3094":33256325,"3095":16746417,"3096":19879454,"3097":2155220,"3098":5207133,"3099":8036743,"3100":1555510,"3101":11571240,"3102":2266391,"3103":914035,"3104":1627519,"3105":2354432,"3106":12360113,"3107":12751374,"3110":583117,"3112":71017848,"3113":213603082,"3114":223825667,"3115":129372336,"3116":370446347,"3117":6306503,"3118":33531988,"3119":78790691,"3121":88973627,"3122":83511529,"3123":58589740,"3124":38137998,"3125":102872447,"3126":66712845,"3127":18707036,"3133":19117316,"3137":26173099,"3138":1551641,"3139":5597948,"3140":21883898,"3141":4691327,"3142":57771027,"3143":106571167,"3144":75574329,"3145":152546019,"3146":48480396,"3147":31552822,"3148":44879087,"3149":26313843,"3150":22202462,"3151":7385944,"3156":140305,"3158":85334,"3159":44110,"3160":7837614,"3161":1354016,"3163":583993,"3165":8339882,"3166":21724194,"3167":66088752,"3169":54590097,"3170":69751017,"3171":82215850,"3173":50963437,"3174":136785751,"3181":160035,"3185":27516155,"3186":629376,"3187":10706778,"3188":19066295,"3189":16796241,"3190":70937139,"3191":86193092,"3192":75049914,"3193":150623267,"3194":39327980,"3195":36674144,"3196":58509545,"3197":242605870,"3198":17336138,"3199":12516116,"3208":8388971,"3211":583993,"3213":6358760,"3214":9085468,"3215":72520424,"3216":114368722,"3217":90966516,"3218":101662552,"3219":73642319,"3220":12096215,"3221":84115671,"3222":211617396,"3230":6016664,"3232":6527546,"3233":40118846,"3234":135653052,"
Error: failed to open database: unexpected end of JSON input

**Comment by mjentsch** [comment] 2019-05-27 16:02
So looks like the discard stats stored in the DB is corrupt... is it safe to drop it in that case?

**Comment by ashish-goswami** [comment] 2019-05-27 17:11
discard stats maintain stats about value log files, which are used in garbage collection. If it is corrupt, you can try to ignore it. Stats will be formed from the start again when compaction will run next.

**Comment by jarifibrahim** [comment] 2019-05-28 15:11
Maybe we can just drop the discard stats map if we fail to unmarshal it. The map would be populated later anyway.

**Comment by campoy** [comment] 2019-05-28 19:16
Were we able to reproduce this bug? If so, please add the `status/confirmed` label @jarifibrahim 
If we're still figuring out what the root cause feel free to also add `status/needs-attention`.

Also if you're working on it, please assign yourself to the issue.

**Comment by jarifibrahim** [comment] 2019-05-29 11:02
>So looks like the discard stats stored in the DB is corrupt... is it safe to drop it in that case?

@mjentsch Yes, it should be safe to drop the discard map since it will be rebuilt during compactions.

**Comment by manishrjain** [comment] 2019-05-29 22:56
It is safe to drop it but comes at a significant loss of information about doing GC. But, even dropping it is just solving a symptom of a deeper problem.

What's probably happening is that the discard stats is being written to memtable directly for every memtable flush. If this stat is *huge* (like in this case), it takes up a big chunk of of the table, which is bad. Secondly, if the size doesn't fit into uint16, then the value probably ends up getting truncated. And therefore, when we try to parse it back, it doesn't unmarshal properly. This needs a test to verify.

What we should be doing is to treat the stats just like we treat values larger than ValueThreshold. It should go through value log and only a pointer should be stored in memtable. So, this should use the normal transaction API to write. And it should not be written on every memtable flush. Instead, it should be written lazily after a few updates have been made (how many is subjective, but we can put something reasonable).

@jarifibrahim @ashish-goswami : Can you verify my hypothesis? And also make changes to the codebase accordingly. What #835 does is only fixing the symptoms, not the problem.

**Comment by jarifibrahim** [comment] 2019-05-30 16:11
@manishrjain You were correct. Thanks for pointing this out.
Here's a test that confirms your hypothesis
```go
func TestDiscardMapTooBig(t *testing.T) {
	createDiscardStats := func() map[uint32]int64 {
		stat := map[uint32]int64{}
		for i := uint32(0); i < 8000; i++ {
			stat[i] = 0
		}
		return stat
	}

	fmt.Println("max uint16", math.MaxUint16)
	dir, err := ioutil.TempDir(".", "badger")
	require.NoError(t, err)
	defer os.RemoveAll(dir)

	ops := DefaultOptions
	ops.Dir = dir
	ops.ValueDir = dir
	db, err := Open(ops)
	require.NoError(t, err, "error while openning db")

	// Add some data so that memtable flush happens on close
	txn := db.NewTransaction(true)
	defer txn.Discard()
	txn.Set([]byte("foo"), []byte("bar"))
	txn.Commit()

	// overwrite discardstat with large value
	db.vlog.lfDiscardStats = &lfDiscardStats{
		m: createDiscardStats(),
	}

	db.Close()
	// reopen the same DB
	db, err = Open(ops)
	require.NoError(t, err, "error while openning db")
	defer db.Close()
}
```
This outputs
```
=== RUN   TestDiscardMapTooBig
max uint16 65535
badger 2019/05/30 21:37:34 INFO: All 0 tables opened in 0s
badger 2019/05/30 21:37:34 DEBUG: Storing value log head: {Fid:0 Len:42 Offset:36}
DiscardStat size while adding: 70891
badger 2019/05/30 21:37:34 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2019/05/30 21:37:34 INFO: Running for level: 0
badger 2019/05/30 21:37:34 DEBUG: LOG Compact. Added 3 keys. Skipped 0 keys. Iteration took: 35.187µs
badger 2019/05/30 21:37:34 DEBUG: Discard stats: map[]
badger 2019/05/30 21:37:34 INFO: LOG Compact 0->1, del 1 tables, add 1 tables, took 2.189443ms
badger 2019/05/30 21:37:34 INFO: Compaction for level: 0 DONE
badger 2019/05/30 21:37:34 INFO: Force compaction on level 0 done
badger 2019/05/30 21:37:35 INFO: All 1 tables opened in 0s
DiscardStat size while retrieving: 5355
--- FAIL: TestDiscardMapTooBig (0.03s)
    /home/ibrahim/Projects/go/src/github.com/dgraph-io/badger/db_test.go:1848: 
        	Error Trace:	db_test.go:1848
        	Error:      	Received unexpected error:
        	            	unexpected end of JSON input
        	Test:       	TestDiscardMapTooBig
        	Messages:   	error while openning db
FAIL
FAIL	github.com/dgraph-io/badger	0.035s
Error: Tests failed.
```

**Comment by jarifibrahim** [comment] 2019-05-31 15:42
>And it should not be written on every memtable flush. Instead, it should be written lazily after a few updates have been made (how many is subjective, but we can put something reasonable).

@manishrjain How about updating the discard stats after every X flushes (X can be any number) and also updating it when DB closes? 

We could also do a time-based discard stat update but that would mean we're inserting entries in the DB even when the DB is not active.

**Comment by campoy** [comment] 2019-06-14 23:57
Hey @jarifibrahim, this issue is blocking the release of v2.0.0.

Could you give an estimate of when it could be solved? Or maybe, is this bug not important and can be fixed in later releases?

**Comment by jarifibrahim** [comment] 2019-06-16 10:03
@campoy We have https://github.com/dgraph-io/badger/pull/858 almost ready to merge. We should be able to get in merged tomorrow.

**Closed** 2019-06-18 08:24 UTC
Labels: area/dataloss, kind/bug, status/accepted
