### ISSUE TITLE
Inconsistent backup/restore on deleted keys

### ISSUE THREAD

**Issue by cyril-schmitt** [dgraph-io/badger#739] opened 2019-03-11 09:17 UTC
Hello,

I have some issue when i use badger. Not sure if it's my fault (bad configuration) or a bug.
here some details.

**What happened:**

When i delete keys and create a backup, after reload fresh backup file, keys are back.

**What you expected to happen:**

I would like have the same "View" result before and after backup/restore.

**How to reproduce it**

With this simple code, View 2 and 3 should have the same result, but it's not the case.
I see that the value is empty but in the case where you use "View" with option (PrefetchValues: false), it will not work, because you need to load value to see if it's empty.

```
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/badger"
)

func View(db *badger.DB) {
	db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.PrefetchSize = 10
		it := txn.NewIterator(opts)
		defer it.Close()
		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.Key()
			v, _ := item.Value()
			fmt.Printf("key=%s, value=%d , version=%v, meta=%v\n", k, v, item.Version(), item.UserMeta())
		}
		return nil
	})
}

func Set(db *badger.DB) {
	err := db.Update(func(txn *badger.Txn) error {
		err := txn.Set([]byte("keyOne"), []byte("42"))
		if err != nil {
			return err
		}
		err = txn.Set([]byte("keyTow"), []byte("21"))
		return err
	})
	if err != nil {
		fmt.Printf("%v\n", err)
	}
}

func Remove(db *badger.DB) {
	err := db.Update(func(txn *badger.Txn) error {
		err := txn.Delete([]byte("keyOne"))
		return err
	})
	if err != nil {
		fmt.Printf("%v\n", err)
	}
}

func CreateBackup(db *badger.DB) {
	f, err := os.Create("backup.db")
	if err != nil {
		fmt.Printf("%v\n", err)
	}
	w := bufio.NewWriter(f)
	_, err = db.Backup(w, 0)
	if err != nil {
		fmt.Printf("%v\n", err)
	}
	w.Flush()
}

func LoadBackup(db *badger.DB) {
	file, err := os.Open("backup.db")
	defer file.Close()
	if err != nil {
		fmt.Printf("%v\n", err)
	}

	err = db.Load(file)
	if err != nil {
		fmt.Printf("%v\n", err)
	}
}

func main() {
	opts := badger.DefaultOptions
	opts.Dir = "badger"
	opts.ValueDir = "badger"
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	fmt.Println("Set Value")
	Set(db)
	fmt.Println("===== VIEW 1 BEGIN -")
	View(db)
	fmt.Println("Remove Value")
	Remove(db)
	fmt.Println("===== VIEW 2 BEGIN -")
	View(db)
	fmt.Println("===== VIEW END ---")

	fmt.Println("GC")
	err = db.RunValueLogGC(0.5)
	if err == nil {
		log.Fatal(err)
	}

	fmt.Println("Create Backup")
	CreateBackup(db)
	fmt.Println("Load Backup")
	LoadBackup(db)
	fmt.Println("===== VIEW 3 BEGIN -")
	View(db)
	fmt.Println("===== VIEW END ---")
}

```

**Current Output:**

```bash
./test                                                                                                                                                                                                      
2019/03/11 09:59:18 Replaying from value pointer: {Fid:0 Len:0 Offset:0}
2019/03/11 09:59:18 Iterating file id: 0
2019/03/11 09:59:18 Iteration took: 20.336µs
Set Value
===== VIEW 1 BEGIN -
key=keyOne, value=[52 50] , version=1, meta=0
key=keyTow, value=[50 49] , version=1, meta=0
Remove Value
===== VIEW 2 BEGIN -
key=keyTow, value=[50 49] , version=1, meta=0
===== VIEW END ---
GC
Create Backup
Load Backup
===== VIEW 3 BEGIN -
key=keyOne, value=[] , version=2, meta=0
key=keyTow, value=[50 49] , version=1, meta=0
===== VIEW END ---
```

**Environment:**

- go version go1.11.5 darwin/amd64
- badger tag 1.5.4

**Comment by cyril-schmitt** [comment] 2019-03-11 09:21
**Current Output:**

```bash
./test                                                                                                                                                                                                      
2019/03/11 09:59:18 Replaying from value pointer: {Fid:0 Len:0 Offset:0}
2019/03/11 09:59:18 Iterating file id: 0
2019/03/11 09:59:18 Iteration took: 20.336µs
Set Value
===== VIEW 1 BEGIN -
key=keyOne, value=[52 50] , version=1, meta=0
key=keyTow, value=[50 49] , version=1, meta=0
Remove Value
===== VIEW 2 BEGIN -
key=keyTow, value=[50 49] , version=1, meta=0
===== VIEW END ---
GC
Create Backup
Load Backup
===== VIEW 3 BEGIN -
key=keyOne, value=[] , version=2, meta=0
key=keyTow, value=[50 49] , version=1, meta=0
===== VIEW END ---
```

**Comment by rohanil** [comment] 2019-04-03 14:20
This is fixed in https://github.com/dgraph-io/badger/commit/ba13ac7f185bab39d8e09c03f74e88014879d764 on master

**Comment by jarifibrahim** [comment] 2019-04-10 11:56
@cyril-schmitt Looks like this issue has been fixed. I ran your script against the latest master and couldn't reproduce the issue. 
```
➜  foo go run main.go
Set Value
===== VIEW 1 BEGIN -
key=keyOne, value=[52 50] , version=10, meta=0
key=keyTow, value=[50 49] , version=10, meta=0
Remove Value
===== VIEW 2 BEGIN -
key=keyTow, value=[50 49] , version=10, meta=0
===== VIEW END ---
GC
Create Backup
Load Backup
===== VIEW 3 BEGIN -
key=keyTow, value=[50 49] , version=10, meta=0
===== VIEW END ---
```
Can you please try the latest master?
I'm closing this issue for now. Feel free to reopen the issue if you encounter it again.

**Closed by jarifibrahim** 2019-04-10 11:56 UTC
