### ISSUE TITLE
DropAll doesn't work properly

### ISSUE THREAD

**Issue by xuemao** [dgraph-io/badger#777] opened 2019-04-22 08:32 UTC
I made a very simple test as follows:
1. Use badger.Open to create a DB in a local directory. Write some data into it and then make a query, make sure the data is read out correctly.
2. Use badger.Close to close the DB. And then use badger.OpenManaged to open the DB by passing in the same directory. Run DropAll and then Close on the managed DB.
3. Use badger.Open again and run the same query. In theory I should not be able to get back any data because the DB has been cleaned up. But I did get back the data I wrote in step 1.

Is this a bug or am I using these APIs in a wrong way? Please help. Thanks!

**Comment by tpihl** [comment] 2019-04-22 08:34
I think DropAll only is available for Managed mode. I ran into the same issue. Wrote my own :)

	err := db.Update(func(txn *badger.Txn) error {

		opt := badger.DefaultIteratorOptions
		opt.PrefetchValues = false

		it := txn.NewIterator(opt)
		defer it.Close()

		for it.Rewind(); it.Valid(); it.Next() {
			key := it.Item().KeyCopy(nil)

			err := txn.Delete(key)
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

**Comment by jarifibrahim** [comment] 2019-04-23 06:37
@xuemao `DropAll` seems to be working fine for me. Take a look at the `drop_all.go` file below. I load the DB with 1 million Key-values and then ran `DropAll` on the same DB. The `SS Tables` and the `value log` files were removed. 
```
$ ls
drop_all.go

$ /bin/cat drop_all.go
package main

import (
	"log"

	"github.com/dgraph-io/badger"
)

func main() {
	opts := badger.DefaultOptions
	opts.Dir = "/tmp/dropalltest"
	opts.ValueDir = "/tmp/dropalltest"
	db, err := badger.OpenManaged(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.DropAll()
}

$ badger fill -m 1 --dir /tmp/dropalltest
Listening for /debug HTTP requests at port: 8080
badger 2019/04/23 12:02:37 INFO: All 0 tables opened in 0s
badger 2019/04/23 12:02:37 INFO: Written keys: 100000
badger 2019/04/23 12:02:38 INFO: Written keys: 200000
badger 2019/04/23 12:02:38 INFO: Written keys: 300000
badger 2019/04/23 12:02:38 INFO: Written keys: 400000
badger 2019/04/23 12:02:38 INFO: Written keys: 500000
badger 2019/04/23 12:02:38 INFO: Written keys: 600000
badger 2019/04/23 12:02:38 INFO: Written keys: 700000
badger 2019/04/23 12:02:39 INFO: Written keys: 800000
badger 2019/04/23 12:02:39 INFO: Written keys: 900000
badger 2019/04/23 12:02:39 INFO: Written keys: 1000000
badger 2019/04/23 12:02:40 DEBUG: Storing value log head: {Fid:0 Len:42 Offset:159379894}
badger 2019/04/23 12:02:40 INFO: 1000000 keys written. Time taken: 2.764712979s
badger 2019/04/23 12:02:40 DEBUG: Storing value log head: {Fid:0 Len:43 Offset:190000378}
badger 2019/04/23 12:02:40 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2019/04/23 12:02:40 INFO: Running for level: 0
badger 2019/04/23 12:02:41 DEBUG: LOG Compact. Added 1000002 keys. Skipped 0 keys. Iteration took: 339.013457ms
badger 2019/04/23 12:02:41 DEBUG: Discard stats: map[]
badger 2019/04/23 12:02:41 INFO: LOG Compact 0->1, del 2 tables, add 1 tables, took 755.37151ms
badger 2019/04/23 12:02:41 INFO: Compaction for level: 0 DONE
badger 2019/04/23 12:02:41 INFO: Force compaction on level 0 done
badger 2019/04/23 12:02:41 INFO: DB.Close. Error: <nil>. Time taken: 1.189495884s

$ ls
000000.vlog  000001.vlog  000003.sst  drop_all.go  MANIFEST

$ go run drop_all.go
badger 2019/04/23 12:02:54 INFO: All 1 tables opened in 185ms
badger 2019/04/23 12:02:54 DEBUG: Value Log Discard stats: map[]
badger 2019/04/23 12:02:54 INFO: Replaying file id: 0 at offset: 190000421
badger 2019/04/23 12:02:54 INFO: Replay took: 6.75µs
badger 2019/04/23 12:02:54 INFO: Replaying file id: 1 at offset: 0
badger 2019/04/23 12:02:54 INFO: Replay took: 4.19µs
badger 2019/04/23 12:02:54 INFO: DropAll called. Blocking writes...
badger 2019/04/23 12:02:54 INFO: Writes flushed. Stopping compactions now...
badger 2019/04/23 12:02:54 INFO: Deleted 1 SSTables. Now deleting value logs...
badger 2019/04/23 12:02:54 INFO: Value logs deleted. Creating value log file: 0
badger 2019/04/23 12:02:54 INFO: Deleted 2 value log files. DropAll done.
badger 2019/04/23 12:02:54 INFO: Resuming writes
badger 2019/04/23 12:02:54 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}

$ ls
000000.vlog  drop_all.go  MANIFEST

$ du -lh ./*
0	./000000.vlog
4.0K	./drop_all.go
4.0K	./MANIFEST
```

@xuemao Can you try running `DropAll` once again? I guess it will work, if not, please help me with a script to reproduce your issue.

**Comment by jarifibrahim** [comment] 2019-04-23 06:40
>I think DropAll only is available for Managed mode. I ran into the same issue. Wrote my own :)

@tpihl `DropAll` should work in both, managed and unmanaged mode. The script you have provided would insert more entries into the database. `Delete` entries are also added to the database, they are stored with a delete marker. If you wish you clean up all the key-values and associated files, I suggest you use the `DropAll` API.

**Comment by xuemao** [comment] 2019-04-23 07:02
@jarifibrahim , I think the difference is that I did all the steps I described in my post in one script execution (one process). It's like

```
  opts := badger.DefaultOptions
  opts.SyncWrites = false
  opts.Dir = dir
  opts.ValueDir = dir
  var err error
  Db, err = badger.Open(opts)
  if err != nil {
    log.Panic(err)
  }

  // Write data
  // Query data make sure it's there
  Db.Close()

  // Then do the DropAll
  opts = badger.DefaultOptions
  opts.Dir = dir
  opts.ValueDir = dir
  managedDb, err := badger.OpenManaged(opts)
  if err != nil {
    log.Panic(err)
  }
  if err := managedDb.DropAll(); err != nil {
    log.Panic(err)
  }
  if err := managedDb.Close(); err != nil {
    log.Panic(err)
  }

  // Now reopen the normal Db
  opts = badger.DefaultOptions
  opts.SyncWrites = false
  opts.Dir = dir
  opts.ValueDir = dir
  var err error
  Db, err = badger.Open(opts)
  if err != nil {
    log.Panic(err)
  }
  
  // Query the data, sadly it's still there.

```

I made a work-around by deleting the whole db data folder instead of using DropAll like this:

```
  cmd := exec.Command("rm", "-rf", dir)
  if err := cmd.Run(); err != nil {
    panic(err)
  }
```

And it works well. When I open the Db again, no data is returned from the query.

BUT very interestingly, if I don't remove the whole dir, instead remove all the files under that dir (including hidden files), aka leaving an empty dir. like this

```
  cmd := exec.Command("rm", "-rf", "dir/*", "dir/.*")
  if err := cmd.Run(); err != nil {
    panic(err)
  }
```

It won't work, when I open the DB again, and then do the query, the data is returned. LOL. I must be doing something crazily wrong. :p

**Comment by jarifibrahim** [comment] 2019-04-23 09:53
>BUT very interestingly, if I don't remove the whole dir, instead remove all the files under that dir (including hidden files), aka leaving an empty dir. like this
>```
>  cmd := exec.Command("rm", "-rf", "dir/*", "dir/.*")
>  if err := cmd.Run(); err != nil {
>    panic(err)
>  }
>```
>It won't work, when I open the DB again, and then do the query, the data is returned. LOL. I must be doing something crazily wrong. :p

@xuemao The wildcard `*` won't work directly. You will have to use either https://golang.org/pkg/path/filepath/#Glob or something like
```sh
cmd := exec.Command("/bin/sh", "-c", "rm -rf /tmp/dropalltestdata/*")
if err := cmd.Run(); err != nil {
	panic(err)
}
```

@xuemao I wrote this https://gist.github.com/jarifibrahim/4b1e4c111f98c7922068571548395d9f based on how you're using the `DropAll` API and it works fine for me. I get the following output
```
$ go run drop_all.go
badger 2019/04/23 15:20:29 INFO: All 0 tables opened in 0s
Total Count before DropAll: 1000
badger 2019/04/23 15:20:29 DEBUG: Storing value log head: {Fid:0 Len:42 Offset:37890}
badger 2019/04/23 15:20:29 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2019/04/23 15:20:29 INFO: Running for level: 0
badger 2019/04/23 15:20:29 DEBUG: LOG Compact. Added 1002 keys. Skipped 0 keys. Iteration took: 580.673µs
badger 2019/04/23 15:20:29 DEBUG: Discard stats: map[]
badger 2019/04/23 15:20:29 INFO: LOG Compact 0->1, del 1 tables, add 1 tables, took 18.173186ms
badger 2019/04/23 15:20:29 INFO: Compaction for level: 0 DONE
badger 2019/04/23 15:20:29 INFO: Force compaction on level 0 done
badger 2019/04/23 15:20:29 INFO: All 1 tables opened in 0s
badger 2019/04/23 15:20:29 DEBUG: Value Log Discard stats: map[]
badger 2019/04/23 15:20:29 INFO: Replaying file id: 0 at offset: 37932
badger 2019/04/23 15:20:29 INFO: Replay took: 10.03µs
badger 2019/04/23 15:20:29 INFO: DropAll called. Blocking writes...
badger 2019/04/23 15:20:29 INFO: Writes flushed. Stopping compactions now...
badger 2019/04/23 15:20:29 INFO: Deleted 1 SSTables. Now deleting value logs...
badger 2019/04/23 15:20:29 INFO: Value logs deleted. Creating value log file: 0
badger 2019/04/23 15:20:29 INFO: Deleted 1 value log files. DropAll done.
badger 2019/04/23 15:20:29 INFO: Resuming writes
badger 2019/04/23 15:20:29 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
badger 2019/04/23 15:20:29 INFO: All 0 tables opened in 0s
badger 2019/04/23 15:20:29 INFO: Replaying file id: 0 at offset: 0
badger 2019/04/23 15:20:29 INFO: Replay took: 9.9µs
Total Count after DropAll: 0
badger 2019/04/23 15:20:29 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}

```

**Comment by tpihl** [comment] 2019-04-26 05:26
> > I think DropAll only is available for Managed mode. I ran into the same issue. Wrote my own :)
> 
> @tpihl `DropAll` should work in both, managed and unmanaged mode. The script you have provided would insert more entries into the database. `Delete` entries are also added to the database, they are stored with a delete marker. If you wish you clean up all the key-values and associated files, I suggest you use the `DropAll` API.

That seems to be the case only in master, not in the referrable stable release 1.53 or 1.54. DropAll is not present in db.go in those versions.

**Comment by jarifibrahim** [comment] 2019-04-26 07:30
>That seems to be the case only in master, not in the referrable stable release 1.53 or 1.54. DropAll is not present in db.go in those versions.

@tpihl You are correct. Earlier the `DropAll` API would work only in the managed mode.

**Comment by jarifibrahim** [comment] 2019-04-29 11:46
@xuemao Can we close this issue?

**Closed** 2019-05-01 20:07 UTC
Labels: question
