### ISSUE TITLE
Memory/Goroutine Leak

### ISSUE THREAD

**Issue by h12w** [dgraph-io/badger#421] opened 2018-02-23 08:05 UTC
## Description

In our production code, multiple BadgerDB files are periodically opened, scanned and closed. The memory consumption keeps increasing after each loop.

I have extracted a minimum test demo to reproduce this issue.

After fixing one major leak by PR #426, the problem might have been fixed already, and I will keep monitoring our production service to see if there are any further leaks.

### Test code

https://github.com/h12w/badgerleak

### Reproduction steps

```
git clone https://github.com/h12w/badgerleak.git
cd badgerleak
go build
./badgerleak

# in another shell
watch "ps x -o command,rss | grep -v grep | grep badgerleak"
```

### Test environment

```
go version go1.10 darwin/amd64
```

```
go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/w/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/w/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/vz/gfwxtk8n2qd4y7ftq52vc1hm0000gn/T/go-build206822171=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Memory profiling diff result

```
go tool pprof -base base.heap ~/go/src/h12.me/badgerleak/badgerleak cur.heap
File: badgerleak
Type: inuse_space
Time: Feb 24, 2018 at 2:51pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 748.83MB, 100% of 748.83MB total
      flat  flat%   sum%        cum   cum%
  748.83MB   100%   100%   748.83MB   100%  github.com/dgraph-io/badger/skl.NewSkiplist
         0     0%   100%   748.83MB   100%  github.com/dgraph-io/badger.Open
         0     0%   100%   748.83MB   100%  main.leakFast
         0     0%   100%   748.83MB   100%  main.main
         0     0%   100%   748.83MB   100%  main.openDB
         0     0%   100%   748.83MB   100%  runtime.main
```

### Goroutine profile

```go
pprof.Lookup("goroutine").WriteTo(os.Stdout, 1)
```

It shows the goroutine numbers are increasing:

```
goroutine profile: total 23
21 @ 0x102e6da 0x102e78e 0x103edf4 0x103ea19 0x1063699 0x13403d6 0x134076b 0x13404ce 0x132b577 0x132b6f2 0x134421b 0x105ab41
#	0x103ea18	sync.runtime_Semacquire+0x38					/usr/local/go/src/runtime/sema.go:56
#	0x1063698	sync.(*RWMutex).RLock+0x48					/usr/local/go/src/sync/rwmutex.go:50
#	0x13403d5	github.com/dgraph-io/badger.(*valueLog).getFileRLocked+0xc5	/Users/w/go/src/github.com/dgraph-io/badger/value.go:754
#	0x134076a	github.com/dgraph-io/badger.(*valueLog).readValueBytes+0x4a	/Users/w/go/src/github.com/dgraph-io/badger/value.go:779
#	0x13404cd	github.com/dgraph-io/badger.(*valueLog).Read+0x7d		/Users/w/go/src/github.com/dgraph-io/badger/value.go:768
#	0x132b576	github.com/dgraph-io/badger.(*Item).yieldItemValue+0x1e6	/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:130
#	0x132b6f1	github.com/dgraph-io/badger.(*Item).prefetchValue+0x31		/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:140
#	0x134421a	github.com/dgraph-io/badger.(*Iterator).fill.func1+0x2a		/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:444

1 @ 0x102e6da 0x102972a 0x1028da7 0x109819b 0x109821d 0x109a668 0x118a772 0x11a2b1e 0x11a1159 0x1284bef 0x1283985 0x12836d9 0x128471a 0x105ab41
#	0x1028da6	internal/poll.runtime_pollWait+0x56		/usr/local/go/src/runtime/netpoll.go:173
#	0x109819a	internal/poll.(*pollDesc).wait+0x9a		/usr/local/go/src/internal/poll/fd_poll_runtime.go:85
#	0x109821c	internal/poll.(*pollDesc).waitRead+0x3c		/usr/local/go/src/internal/poll/fd_poll_runtime.go:90
#	0x109a667	internal/poll.(*FD).Accept+0x1a7		/usr/local/go/src/internal/poll/fd_unix.go:372
#	0x118a771	net.(*netFD).accept+0x41			/usr/local/go/src/net/fd_unix.go:238
#	0x11a2b1d	net.(*TCPListener).accept+0x2d			/usr/local/go/src/net/tcpsock_posix.go:136
#	0x11a1158	net.(*TCPListener).AcceptTCP+0x48		/usr/local/go/src/net/tcpsock.go:246
#	0x1284bee	net/http.tcpKeepAliveListener.Accept+0x2e	/usr/local/go/src/net/http/server.go:3216
#	0x1283984	net/http.(*Server).Serve+0x1a4			/usr/local/go/src/net/http/server.go:2770
#	0x12836d8	net/http.(*Server).ListenAndServe+0xa8		/usr/local/go/src/net/http/server.go:2711
#	0x1284719	net/http.ListenAndServe+0x79			/usr/local/go/src/net/http/server.go:2969

1 @ 0x134d828 0x134d630 0x134a174 0x1355fc0 0x1355f40 0x102e282 0x105ab41
#	0x134d827	runtime/pprof.writeRuntimeProfile+0x97	/usr/local/go/src/runtime/pprof/pprof.go:679
#	0x134d62f	runtime/pprof.writeGoroutine+0x9f	/usr/local/go/src/runtime/pprof/pprof.go:641
#	0x134a173	runtime/pprof.(*Profile).WriteTo+0x3e3	/usr/local/go/src/runtime/pprof/pprof.go:310
#	0x1355fbf	main.leakFast+0x6f			/Users/w/go/src/h12.me/badgerleak/main.go:53
#	0x1355f3f	main.main+0x1f				/Users/w/go/src/h12.me/badgerleak/main.go:20
#	0x102e281	runtime.main+0x211			/usr/local/go/src/runtime/proc.go:198
```

### Blocked goroutines that should have exited

```
goroutine 109 [semacquire]:
sync.runtime_Semacquire(0xc42018219c)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc420182190)
	/usr/local/go/src/sync/rwmutex.go:50 +0x49
github.com/dgraph-io/badger.(*valueLog).getFileRLocked(0xc420198128, 0x0, 0x0, 0x0, 0x0)
	/Users/w/go/src/github.com/dgraph-io/badger/value.go:754 +0xc6
github.com/dgraph-io/badger.(*valueLog).readValueBytes(0xc420198128, 0x13c00000000, 0x13c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/w/go/src/github.com/dgraph-io/badger/value.go:779 +0x4b
github.com/dgraph-io/badger.(*valueLog).Read(0xc420198128, 0x13c00000000, 0x13c, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/w/go/src/github.com/dgraph-io/badger/value.go:768 +0x7e
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc42018c420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:130 +0x1e7
github.com/dgraph-io/badger.(*Item).prefetchValue(0xc42018c420)
	/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:140 +0x32
github.com/dgraph-io/badger.(*Iterator).fill.func1(0xc42018c420)
	/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:444 +0x2b
created by github.com/dgraph-io/badger.(*Iterator).fill
	/Users/w/go/src/github.com/dgraph-io/badger/iterator.go:442 +0x27e
```

### One Cause

After some analysis, the cause seems that the prefetch goroutines are blocked by `ret.lock.RLock()`

value.go:746:
```go
func (vlog *valueLog) getFileRLocked(fid uint32) (*logFile, error) {
	vlog.filesLock.RLock()
	defer vlog.filesLock.RUnlock()
	ret, ok := vlog.filesMap[fid]
	if !ok {
		// log file has gone away, will need to retry the operation.
		return nil, ErrRetry
	}
	ret.lock.RLock() // BLOCKED HERE
	return ret, nil
}
```

which is caused by `f.lock.Lock()`

value.go:554:
```go
func (vlog *valueLog) Close() error {
	vlog.elog.Printf("Stopping garbage collection of values.")
	defer vlog.elog.Finish()

	var err error
	for id, f := range vlog.filesMap {

		// THIS LOCK prevents the prefetch goroutine exiting
		f.lock.Lock() // We won’t release the lock.
		if munmapErr := y.Munmap(f.fmap); munmapErr != nil && err == nil {
			err = munmapErr
		}

		if id == vlog.maxFid {
			// truncate writable log file to correct offset.
			if truncErr := f.fd.Truncate(
				int64(vlog.writableLogOffset)); truncErr != nil && err == nil {
				err = truncErr
			}
		}

		if closeErr := f.fd.Close(); closeErr != nil && err == nil {
			err = closeErr
		}

	}
	return err
}
```

**Comment by manishrjain** [comment] 2018-02-27 00:04
We were not waiting for the goroutines created by the iterator to finish before closing iterator. I've sent a PR to fix that. Your code works OK now.

**Comment by manishrjain** [comment] 2018-02-27 00:22
This issue is fixed in master. Please verify that the issue is fixed. Feel free to reopen if it isn't.

**Closed by manishrjain** 2018-02-27 00:22 UTC
Labels: cleanup
