### ISSUE TITLE
How to compress space?

### ISSUE THREAD

**Issue by ywui** [dgraph-io/badger#747] opened 2019-03-26 05:55 UTC
look  title, :xd

**Comment by jarifibrahim** [comment] 2019-04-10 11:57
You can try running the garbage collector https://github.com/dgraph-io/badger#garbage-collection

**Comment by jarifibrahim** [comment] 2019-05-02 14:51
Duplicate of https://github.com/dgraph-io/badger/issues/792

**Closed by jarifibrahim** 2019-05-02 14:51 UTC
