### ISSUE TITLE
Badger Writes Should Return an Error if DB is Closed

### ISSUE THREAD

**Issue by notbdu** [dgraph-io/badger#420] opened 2018-02-21 22:13 UTC
Currently, writes to a closed database result in a panic: 
```
panic: send on closed channel

goroutine 412 [running]:
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc42036a600, 0xc420bed2b0, 0x2, 0x2, 0xc420293bb8, 0x10, 0x89

        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/db.go:589 +0x168
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).batchSet(0xc42036a600, 0xc420bed2b0, 0x2, 0x2, 0x4, 0x8)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/db.go:659 +0x4d
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*Txn).Commit(0xc420be3440, 0x0, 0x0, 0x0)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/transaction.go:500 +0x847
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).Update(0xc42036a600, 0xc420293d70, 0x0, 0x0)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/transaction.go:568 +0xd3
```

Ideally, writes to a closed DB should probably return an exported error named `ErrBadgerClosed` or something similar.

**Comment by manishrjain** [comment] 2018-03-19 18:07
Documentation needs to be clarified.

**Comment by manishrjain** [comment] 2018-04-03 01:43
Duplicate of #374 .

**Closed by manishrjain** 2018-04-03 01:43 UTC
Labels: documentation, help wanted, low-pri
