### ISSUE TITLE
Mobile support.

### ISSUE THREAD

**Issue by joeblew99** [dgraph-io/badger#244] opened 2017-09-23 07:28 UTC
I currently use boltdb on mobiles.
In bolts readme there are some minor adjustments required for mobiles.

The code is then compiled into an aar or framework file for each is using gomobile.

It's stupid easy to us :)

Would the team be open to looking into mobile support ?

**Comment by manishrjain** [comment] 2017-09-23 12:15
Interesting. That's not something we'll actively work on, but if the you or others in the community want to send us PRs to enable mobile support, we'd be open to it; as long as it doesn't significantly add complexity to the code base.

**Comment by joeblew99** [comment] 2017-09-26 08:22
i think there might be a misunderstanding.

Supporting mobile is not like the code needs to be change.
Its more about the way you code your android and ios code to find the boltdb.

Here is the thing you need:
https://github.com/boltdb/bolt#mobile-use-iosandroid

It woudl be a shame for it not to be supported as i know lots of people that use boltdb and also badger on mobile..

**Comment by manishrjain** [comment] 2017-09-26 08:28
Happy to accept a PR for documentation change that's needed to add mobile example.

**Comment by whyrusleeping** [comment] 2017-10-18 15:40
We had troubles building badger on iOS, it seems that this file doesnt compile well there (the syscall doesnt seem to exist): https://github.com/dgraph-io/badger/blob/master/y/file_dsync.go

**Comment by manishrjain** [comment] 2017-10-19 22:35
@deepakjois ^

**Comment by deepakjois** [comment] 2017-10-23 10:28
@whyrusleeping Can this be replicated on a Mac, because I doubt I am going to get access to an iOS device? Do you have some sort of log output which I can look at?

**Comment by whyrusleeping** [comment] 2017-10-23 10:32
Yeah, if you have a mac, you can install gomobile and use it to build for
an iOS target

**Comment by gedw99** [comment] 2018-01-20 22:15
@deepakjois @whyrusleeping 
There is a PR that fixes the DSNCY issue kindly submitted ..
https://github.com/dgraph-io/badger/pull/378

**Comment by deepakjois** [comment] 2018-01-22 03:06
I think #378 just slipped through the cracks, maybe because of the CLA confustion. Sorry about that. I will take a look at it today, and make the changes myself.

If somebody is willing to make a script to do CI on these platforms, we would happily accept a pull request.

**Comment by gedw99** [comment] 2018-01-22 09:20
hehe. no worries !! :)

Ok i cant promise a CI script that soon. Snowed under. If i am forced to make one for work, but def come back here and post it

thanks

**Comment by rucuriousyet** [comment] 2018-04-29 23:37
Any updates here? I am using badger for a cross-platform project that I am now trying to port to mobile. I would hate to have to rewrite my backend integration to use boltdb simply because it has mobile support. I think badger would be a much faster database for mobile given that it's optimized for SSD/NAND based systems, and most mobile systems use NAND storage...

**Comment by rucuriousyet** [comment] 2018-04-30 11:43
I might be able to get a demo of badger going on Android later today. I
don't have the tools to get iOS going tho.

-sent from my OnePlus X

**Comment by rucuriousyet** [comment] 2018-04-30 18:54
So I'm sitting in a coffeeshop messing with this now... I integrated a gomobile-producted .aar file and got it imported properly. Now I am encountering this error: `Unable to mmap RDWR log file: invalid argument` with the following code: 

```go
package badgerdb

import (
	"errors"
	"log"
	"path"

	"github.com/dgraph-io/badger"
)

func mobilePanic(err error) {
	// noisy errors are easy to hear ;)
	log.Println("!!!BADGERDB_DEMO_APP ERROR ENCOUNTERED!!!")
	log.Fatalln(err)
}

func SupportsBadger(filepath string) bool {
	opts := badger.DefaultOptions
	opts.ValueDir = path.Join(filepath, "/datastore")
	opts.Dir = opts.ValueDir

	db, err := badger.Open(opts)
	if err != nil {
		mobilePanic(err)
	}

	defer db.Close()
	err = db.Update(func(tx *badger.Txn) error {
		return tx.Set([]byte("hello"), []byte("world"))
	})
	if err != nil {
		mobilePanic(err)
	}

	err = db.View(func(tx *badger.Txn) error {
		item, er := tx.Get([]byte("hello"))
		if er != nil {
			return er
		}

		val, er := item.Value()
		if er != nil {
			return er
		}

		if string(val) != "world" {
			return errors.New("invalid value returned by database")
		}

		return nil
	})
	if err != nil {
		mobilePanic(err)
	}

	return true
}
```
It's messy code, I don't have alot of time so Im just trying to get something basic working. If I find more time later this week, I plan to integrate Flutter into a demo with Badger that allows you to read and write string values with a textfield and a set of buttons.

A quick Google search didn't yield any results with the same error, I hope someone on the Badger dev team knows why this is happening/how to fix it.

**Comment by rucuriousyet** [comment] 2018-04-30 18:56
Also, If someone is interested in integrating Flutter with Golang, feel free to hmu as I'd be happy to help. Most of the setup is rather simple and only requires you to edit a few .gradle files, copy your .aar file over and then write the MethodChannel calls required to interop Dart/Flutter and Kotlin (or Java, I chose to use Kotlin).

**Comment by rucuriousyet** [comment] 2018-04-30 22:01
I do but I'm on the road and it's private. I would take a look at the
flutter docs... It's really easy to create a project from a template, then
you just gotta figure out how to import the gobind created library. On
Android it's an aar file

-sent from my OnePlus X

**Comment by manishrjain** [comment] 2018-05-01 00:07
@rucuriousyet : Maybe try by keeping the value log on disk. You can set that in the options. By default, value log is set to mmap, so you can change that.

Actually, tbh, I don't really know what to do for this issue. So, if someone wants to send a PR, I'm happy to accept it.

**Comment by campoy** [comment] 2019-05-28 19:35
What's the current state of this issue?
This has been opened for over a year. We should either fix or close the issue.

Is badger not compiling under certain platforms? Have we been able to reproduce the issue?

**Comment by gedw99** [comment] 2019-05-29 13:50
I have fond that its better to compile the golang code to a shared lib, and so its now just a c lib.
then hook in from whatever you use for the GUI on the Mobile or Desktop.
I use FLutter which can now hook in directly to golang compiled this way.

**Comment by campoy** [comment] 2019-05-29 19:29
So badger currently works well for Mobile and Desktop.

I'll close this issue and we can reopen it later on if new concerns arise.

**Closed by campoy** 2019-05-29 19:29 UTC
Labels: area/documentation, kind/bug, priority/P2, status/more-info-needed
