### ISSUE TITLE
Badger DB (v0.9 & v1.x) not closing in some setups

### ISSUE THREAD

**Issue by ArnoSen** [dgraph-io/badger#355] opened 2017-12-12 17:49 UTC
I need to help to troubleshoot why in some setups, the Badger DB does not close.

It closes properly when I something like below:
NB: dbmanager is just a wrapper as well as 'db'

```
func main() {

  dbman,err := dbmanager.Open("/tmp/badgerclose")
  if err != nil {
    log.Fatal(fmt.Sprintf("Unable to open db: %s\n", err))
  }

  db := dbman.NewDB()

  if writeError := db.Set([]byte("key"), []byte("value")); writeError != nil {
    log.Fatal(fmt.Sprintf("Unable to write key to db: %s\n", writeError))
  }

  c := make (chan bool, 1)
  go shut(c, dbman)

  <-c
}

func shut(c chan bool, dbman *dbmanager.DBManager) {
  err := dbman.Close()
  if err != nil {
    fmt.Printf("Error closing the database: %s\n",err) 
  } else {
    fmt.Println("DB closed properly")
  }
  c <- true
}
```

db.Set: 
```
func (db *DB) Set(key, value []byte) error {
  err := db.bdb.Update(func(tx *badger.Txn) error {
    // txn = transaction
    err := tx.Set(key, value)
    if err != nil {
        return err
    }
    return nil
  })
  return err
}
```

When I am not able to close a Badger DB is when I use it in combination with a http server using the built-in net/http. I pass a pointer to my database in my HTTP handler so all my routes can access the DB. 
After I have called some URL's that have DB interaction, and i try to close the DB, it will never close.
I don't know if this is a bug. 
It would be of great help if you could point in the right direction to determine what is the cause the db does not close and if it is a bug.

Thanks in advance for your support!

**Comment by peterstace** [comment] 2017-12-12 23:04
Hi,

Is it possible for you to create a minimal working example that exhibits the problem? Badger doesn't do any HTTP interactions, so I would be surprised if using it in combination with an HTTP server would be a problem.

**Comment by ArnoSen** [comment] 2017-12-13 15:43
Hi,

I have built a mini version of my from scratch. Sofar I am not able to replicate the issue I have with the full app although I have added more and more details of the old app.

In order to try to find the cause, I have added fmt.Print statements to the Close() method of the Badger lib:
```
(...)
        fmt.Println("badger: RECEIVED A CLOSE")

        db.elog.Printf("Closing database")
        // Stop value GC first.
        fmt.Println("badger: STOP VALUE GC FIRST")
        db.closers.valueGC.SignalAndWait()

        // Stop writes next.
        fmt.Println("badger: STOP WRITES")
        db.closers.writes.SignalAndWait()

        // Now close the value log.
        fmt.Println("badger: CLOSING VLOG")
        if vlogErr := db.vlog.Close(); err == nil {
                fmt.Println("badger: ERROR CLOSING VLOG")
                err = errors.Wrap(vlogErr, "DB.Close")
        }
        fmt.Println("badger: END CLOSE VALUE LOG")

(...)
```

When I close the DB, this is the ouput: 
```
badger: RECEIVED A CLOSE
badger: STOP VALUE GC FIRST
badger: STOP WRITES
badger: CLOSING VLOG
// it stops here
```

I suspect the vlog does not close. Can you assist me to troubleshoot this futher?

**Comment by ArnoSen** [comment] 2017-12-13 16:17
To add to this case:
When I start my http server and close it, then also the badger DB closes properly.
However, after I have ran a query against the db, the db never closes.

**Comment by manishrjain** [comment] 2017-12-13 16:40
Can you try to replicate this without HTTP?

**Comment by ArnoSen** [comment] 2017-12-13 17:07
As I wrote above, when I use http and just open en close the db (so no transactions), closing is always working. When I have ran any transaction that is initiated as a result of a http request, the closing never completes.

When I use badger without http in simple test scripts, I have never had an issue with closing a db.

**Comment by peterstace** [comment] 2017-12-13 22:59
> Sofar I am not able to replicate the issue I have with the full app although I have added more and more details of the old app.

Perhaps it would be easier to go from the other direction - start with your existing app and start removing things. Keep reducing your app (with it still exhibiting the potential bug) until it's a minimum working example.

**Comment by ArnoSen** [comment] 2017-12-14 15:03
@peterstace : I am working on it. I also upgrade to the latest stable Go (version 1.9.2) but the issue is still there

**Comment by ArnoSen** [comment] 2017-12-15 13:38
[bclose.tar.gz](https://github.com/dgraph-io/badger/files/1562748/bclose.tar.gz)

I have create a minimum version that shows the DB not closing.
The file creates a directory 'github.com/arnosen/bclose/' .

You need to build it and then start it. This wil start a HTTP server at port 8443, a log file /tmp/bclose.log and the db location is hardcoded to /tmp/db3 .

To replicate the issue you run enroll.sh . This will do a http request and returns a JSON string that contains a token field value. You will notice that when you stop the server at this point the DB closes fine.

To trigger the issue,  you need to add the token that was returned in the previous command in the file 'causeCloseFailure.sh':
curl -k -H "Content-Type: application/json" -H "X-TOKEN:<put token here>" -X POST  https://localhost:8443/admin/getusers

After you have run the command, you should get this JSON: {"status":"OK"} . If you close the server, you will notice the DB closure takes forever. When you get an access denied message and stop the server process, the DB closes properly.

The key code that triggers the DB closure issue is in server/token.go where a lookup of the user provided token is done in the DB. The DB value is a serialized user object. Serialization has been done using GOB.

The only external dependency is bone but that is just a simple wrapper for routing of HTTP requests.

I have spend quite some time to get this minimum version. Also I have tried to find the cause of the problem myself by doing lot's of tests. I would really appreciate your help to find the cause of this issue.

**Comment by deepakjois** [comment] 2017-12-19 03:51
Thank you for providing the code. I can replicate the issue as you describe it. I will investigate further and update this issue once I have figured out the root cause.

**Comment by deepakjois** [comment] 2017-12-19 04:49
@ArnoSen The problem is in the `DB.Get()` method in the file `server/db/db.go`.

First, let me emphasise this point in the godocs for Badger’s `Item.Value()` method:

> The returned value is only valid as long as item is valid, or transaction is valid. So, if you need to use it outside, please parse or copy it.

You are holding on to the item outside of the transaction which is not the correct behavior. I would modify your method to something like below to copy the value so that it can be used outside of the txn (using `Item.ValueCopy()`):

```Go
//This function gets the value of a key
func (db *DB) Get(key []byte) ([]byte, error) {
	var val []byte

	err := db.bdb.View(func(tx *badger.Txn) error {
		item, err := tx.Get(key)
		if err != nil {
			return err
		}
		val, err = item.ValueCopy(val)
		return err
	})

	if err == badger.ErrKeyNotFound {
		return val, nil
	}
	return val, err
}
```

I am not entirely sure of the root cause, but I suspect that something inside Badger is waiting forever because a reference to the item has escaped outside of the transaction. I will investigate that further.

But you should be able to unblock yourself if you just use `Item` as it is intended and copy the value inside the txn.

**Comment by deepakjois** [comment] 2017-12-19 06:23
So the root cause of the problem is that  calling `item.Value()` acquires a lock on the value log, and inserts a callback that is intended to be called when `txn.Discard()` is called (either by client code or automatically by Badger when `DB.View()` or `DB.Update()` calls finish). This call back releases a lock that is acquired.

Calling `item.Value()` outside of a transaction however (which is undefined behavior), means that we get into a race condition. The lock is acquired, but the callback is never invoked because the transaction has _already been discarded_.

We should make things clearer in the documentation.

**Comment by deepakjois** [comment] 2017-12-19 06:24
Closing this for now. Please re-open if you are still facing the issue even after you call `Item.Value()` correctly.

**Closed by deepakjois** 2017-12-19 06:24 UTC
Labels: investigate

**Comment by ArnoSen** [comment] 2017-12-19 10:03
Thanks for looking into this. Also I appreciate your quick response.

Other then improving the documentation, I would prefer that dependencies are made more explicit in the code (and e.g. a compile error is thrown) so as a developer you cannot run into a situation like this.

But thanks again for the investigating this issue. Keep up the good work!
