### ISSUE TITLE
[BUG]: Deleting keys in bulk doesn't delete all the keys even though the txn contains the expected pending writes

### ISSUE THREAD

**Issue by clarkmcc** [dgraph-io/badger#1825] opened 2022-11-02 14:00 UTC
### What version of Badger are you using?

github.com/dgraph-io/badger/v3 v3.2103.3

### What version of Go are you using?

go version go1.18.5 darwin/arm64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

MacBook Pro (13-inch, M1, 2020)
Apple M1
16 GB RAM

### What steps will reproduce the bug?

```go
package main

import (
	"bytes"
	"fmt"
	"github.com/dgraph-io/badger/v3"
)

func main() {
	db, err := badger.Open(badger.DefaultOptions("").WithInMemory(true))
	if err != nil {
		panic(err)
	}
	n := 200

	// Write 1,000 keys
	err = db.Update(func(txn *badger.Txn) error {
		for i := 0; i < n; i++ {
			err = txn.Set([]byte(fmt.Sprintf("%v", i)), bytes.Repeat([]byte{0}, 1024))
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

	// Check the number of keys
	if getKeyCount(db) != n {
		panic("expected 200 elements")
	}

	// Delete all the elements
	var keys [][]byte
	err = db.Update(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()
		for it.Seek([]byte{}); it.ValidForPrefix([]byte{}); it.Next() {
			keys = append(keys, it.Item().Key())
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	containsDups(keys)

	err = db.Update(func(txn *badger.Txn) error {
		for _, k := range keys {
			err = txn.Delete(k)
			if err != nil {
				return err
			}
		}
		return nil
	})
	if err != nil {
		panic(err)
	}

	// Check again
	if i := getKeyCount(db); i != 0 {
		panic(fmt.Sprintf("expected 0 elements, got %v", i))
	}
}

func getKeyCount(db *badger.DB) (i int) {
	err := db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()
		for it.Seek([]byte{}); it.ValidForPrefix([]byte{}); it.Next() {
			i++
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	return
}

func containsDups(in [][]byte) {
	for i, k := range in {
		for j, v := range in {
			if bytes.Equal(k, v) && i != j {
				fmt.Printf("found dup %v=%v\n", i, j)
			}
		}
	}
}
```

Prints the following
```
found dup 1=0
found dup 2=101
found dup 3=103
found dup 4=104
found dup 5=105
found dup 6=106
found dup 7=107
found dup 8=108
found dup 9=109
found dup 10=110
found dup 11=111
found dup 13=113
found dup 24=124
found dup 35=135
found dup 46=146
found dup 57=157
found dup 68=168
found dup 79=179
found dup 90=190
```

### Expected behavior and actual result.

I expected this code to not panic and for all the keys that I had added, to be deleted. Using the debugger, I verified that all the keys that I deleted do show up in the transaction's pending writes, but only 100 out of 1000 (consistently) are actually deleted. Deleting the keys in a separate transaction from the iterator doesn't seem to make a difference. I saw this issue in an internal project, and then reproduced it with this script.

### Additional information
Another thing that's interesting is that if you set `n` to 100, the problem does not exist. Anything higher results in duplicates.

_No response_

**Comment by xhs** [comment] 2022-11-15 15:37
Similar issue here.

### What version of Badger are you using?

github.com/dgraph-io/badger/v3 v3.2103.4

### What version of Go are you using?

go version go1.18.7 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Thinkpad X1
16GB RAM
Intel i7 x86_64 CPU
Fedora 35

### What steps will reproduce the bug?

I got some real project data in /tmp/xxx/client.

```go
package main

import (
	"github.com/dgraph-io/badger/v3"
	log "github.com/sirupsen/logrus"
)

func main() {
	opts := badger.DefaultOptions("/tmp/xxx/client").WithLogger(log.StandardLogger()).WithLoggingLevel(badger.ERROR)
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}

	prefix := []byte{}
	var count int64
	err = db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			count += 1
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Infof("before: %v\n", count)

	count = 0
	err = db.Update(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			if err = txn.Delete(it.Item().Key()); err != nil {
				return err
			}
			count += 1
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Infof("deleted: %v\n", count)

	count = 0
	var keys [][]byte
	err = db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			count += 1
			keys = append(keys, it.Item().Key())
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Infof("remaining: %v\n", count)

	count = 0
	log.Infof("keys to delete: %v\n", len(keys))
	for _, k := range keys {
		err = db.Update(func(txn *badger.Txn) error {
			return txn.Delete(k)
		})
		if err != nil {
			log.Fatal(err)
		}
		count += 1
	}
	log.Infof("deleted again: %v\n", count)

	count = 0
	err = db.View(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()

		for it.Seek(prefix); it.ValidForPrefix(prefix); it.Next() {
			count += 1
		}
		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Infof("after: %v\n", count)
}
```

I have to run this code several times to delete all the keys.

```shell
➜  test git:(main) ✗ ./test                                    
INFO[0000] before: 606                                  
INFO[0000] deleted: 606                                 
INFO[0000] remaining: 401                               
INFO[0000] keys to delete: 401                          
INFO[0000] deleted again: 401                           
INFO[0000] after: 240                                   
➜  test git:(main) ✗ ./test
INFO[0000] before: 240                                  
INFO[0000] deleted: 240                                 
INFO[0000] remaining: 109                               
INFO[0000] keys to delete: 109                          
INFO[0000] deleted again: 109                           
INFO[0000] after: 5                                     
➜  test git:(main) ✗ ./test
INFO[0000] before: 5                                    
INFO[0000] deleted: 5                                   
INFO[0000] remaining: 0                                 
INFO[0000] keys to delete: 0                            
INFO[0000] deleted again: 0                             
INFO[0000] after: 0
```

I am new to badger and deleting keys while iterating does not seem good practice to me. But as @clarkmcc said deleting the keys in a separate transaction doesn't make a difference.

**Comment by amwolff** [comment] 2022-11-17 18:04
From documentation for `*Item.Key`:

> Key is only valid as long as item is valid, or transaction is valid. If you need to use it outside its validity, please use KeyCopy.

You are using keys outside their validity before copying them. The reason it doesn't work is that the underlying slice of bytes gets reused (the iteration is faster this way if you don't care about keys outside their validity), so you get duplicates, and then you can't delete everything at once.

So this is not a bug. To make it work as you would expect it to:

```diff
	// Delete all the elements
	var keys [][]byte
	err = db.Update(func(txn *badger.Txn) error {
		it := txn.NewIterator(badger.DefaultIteratorOptions)
		defer it.Close()
		for it.Seek([]byte{}); it.ValidForPrefix([]byte{}); it.Next() {
-			keys = append(keys, it.Item().Key())
+			keys = append(keys, it.Item().KeyCopy(nil))
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	containsDups(keys)
```

**Comment by boreq** [comment] 2023-01-20 17:05
I think the difference in signatures of `Value` (accepts a function) and `Key` (does not accept a function) may be confusing. I personally wrongly assumed that since the signature of those two functions is very different the slice returned by `Key` is never reused.

**Comment by zl03jsj** [comment] 2023-03-15 12:13
> From documentation for `*Item.Key`:
> 
> > Key is only valid as long as item is valid, or transaction is valid. If you need to use it outside its validity, please use KeyCopy.
> 
> You are using keys outside their validity before copying them. The reason it doesn't work is that the underlying slice of bytes gets reused (the iteration is faster this way if you don't care about keys outside their validity), so you get duplicates, and then you can't delete everything at once.
> 
> So this is not a bug. To make it work as you would expect it to:
> 
> ```diff
> 	// Delete all the elements
> 	var keys [][]byte
> 	err = db.Update(func(txn *badger.Txn) error {
> 		it := txn.NewIterator(badger.DefaultIteratorOptions)
> 		defer it.Close()
> 		for it.Seek([]byte{}); it.ValidForPrefix([]byte{}); it.Next() {
> -			keys = append(keys, it.Item().Key())
> +			keys = append(keys, it.Item().KeyCopy(nil))
> 		}
> 		return nil
> 	})
> 	if err != nil {
> 		panic(err)
> 	}
> 	containsDups(keys)
> ```
right...or you can use `DropPrefix`

**Comment by xhs** [comment] 2023-03-15 13:19
Yeah... I have learned it the hard way. Typical misuse.

**Comment by mangalaman93** [comment] 2023-03-18 08:46
Closing the issue for now, feel free to reopen it in case you have more questions.

**Closed by mangalaman93** 2023-03-18 08:46 UTC
Labels: kind/bug
