### ISSUE TITLE
Badger Data Loss Challenge: Entry 7

### ISSUE THREAD

**Issue by pradeepyella** [dgraph-io/badger#586] opened 2018-09-24 12:17 UTC
Entry For #570.
badger crashes before writing bitFinTxn, restart badger write values, badger looses all data written to the value log file where bitFinTxn was not written after restart.

Badger truncates only when there are partial entires from one transaction and then entries of other transactions starts(or rewrite keys).
go test -v -run='TestDataLoss$' .
go test -v -run='TestDataLoss2$' .
go test -v -run='TestDataLoss3$' .
```
func TestDataLoss(t *testing.T) {
	dir := "p"
	opts := getTestOptions(dir)
	opts.SyncWrites = true

	kv, err := Open(opts)
	require.NoError(t, err)
	key := func(i int) string {
		return fmt.Sprintf("%d%10d", i, i)
	}
	data := fmt.Sprintf("%10d", 1)
	// This part simulates badger crashing before writing bitFinTx
	e := &Entry{
		Key: y.KeyWithTs([]byte(key(0)), kv.orc.nextTxnTs),
		meta: bitTxn,
		Value: []byte(data),
	}
	kv.orc.nextTxnTs++
	err = kv.batchSet([]*Entry{e})
	require.NoError(t, err)

   /*
The above does the following.
Write this using public API, then truncate the file
This type of failure can happen as claimed in your blog
https://blog.dgraph.io/post/alice/
Only a prefix of data is persisted to file crash.
err := kv.Update(func(txn *Txn) error {
			return txn.Set([]byte(key(i0), []byte(data))
		})
		require.NoError(t, err)

*/
}

func TestDataLoss2(t *testing.T) {
	dir := "p"
	opts := getTestOptions(dir)
	opts.SyncWrites = true

	kv, err := Open(opts)
	require.NoError(t, err)
	key := func(i int) string {
		return fmt.Sprintf("%d%10d", i, i)
	}
	data := fmt.Sprintf("%10d", 1)
	for i := 32; i < 64; i++ {
		err := kv.Update(func(txn *Txn) error {
			return txn.Set([]byte(key(i)), []byte(data))
		})
		require.NoError(t, err)
	}
	for i := 32; i < 64; i++ {
		require.NoError(t, kv.View(func(txn *Txn) error {
			item, err := txn.Get([]byte(key(i)))
			require.NoError(t, err)
			val := getItemValue(t, item)
			require.NotNil(t, val)
			require.True(t, len(val) > 0)
			return nil
		}))
	}
}

func TestDataLoss3(t *testing.T) {
	dir := "p"
	opts := getTestOptions(dir)
	opts.SyncWrites = true

	kv, err := Open(opts)
	require.NoError(t, err)
	key := func(i int) string {
		return fmt.Sprintf("%d%10d", i, i)
	}
	for i := 32; i < 64; i++ {
		require.NoError(t, kv.View(func(txn *Txn) error {
			item, err := txn.Get([]byte(key(i)))
			require.NoError(t, err)
			val := getItemValue(t, item)
			require.NotNil(t, val)
			require.True(t, len(val) > 0)
			return nil
		}))
	}
}
```

**Comment by manishrjain** [comment] 2018-09-25 04:38
If Badger crashes before it has acknowledged the txn write to the user, that txn isn't guaranteed to be durable. As mentioned in the challenge:

> Badger must be run with SyncWrites=true enabled (the default). **Badger only promises durability of successful writes.**

**Comment by pradeepyella** [comment] 2018-09-25 04:42
@manishrjain  Please see the whole example. Badger would delete subsequent writes which were acknowledged.

First Run, badger doesn't acknowledge but writes partial entries.
On restart nothing would be truncated, new writes would be acknwoledged.
On next restart badger would truncate everything from the partial writes, thus we would loose the data which was acknowledged.

**Comment by manishrjain** [comment] 2018-09-25 05:14
Alright, I'll have a look. Looks like the premise of your bug report is that if bitFinTxn isn't written, then Badger would not truncate the log, but keep on appending more entries (after a restart). But, then after another restart, it would?

There should be an easy way to test this. Maybe open Badger in a mount with limited disk space (say using tmpfs). Create a large enough txn which won't fit on it -- so Badger would write half of it and potentially crash due to disk space. Then move the data, and reopen Badger, see whether it fails to return new writes. If it fails, we have an issue. Otherwise, not.

Again, the focus here is on how Badger behaves on public APIs. Mucking up the internals to simulate failure cases is out of scope here.

**Comment by pradeepyella** [comment] 2018-09-25 05:32
Can I atleast use internal api to simulate half of the transaction written to disk before crashing. Rest I would use public APIs.

I don't understand what's the difference between that and real world failure. Are you saying partial transaction entries can't be written in real world. Remaining internal stuff I will change to public APIs except that

**Comment by manishrjain** [comment] 2018-09-25 05:42
Think my above explanation is pretty clear already. If you're unable to simulate a data loss using public APIs and a file system issue that Badger should tolerate (like running out of disk), then you don't have a proof of a data loss.

**Comment by pradeepyella** [comment] 2018-09-25 12:04
I have edited the examples to use real world examples. Only TestDataLoss simulates partial append to a file. 
Simulating non atomic append is difficult( I would need to simulate file system or use some external framework), if disk space is less os would throw error before it even tries to append data.
Please have a look at the following links
https://stackoverflow.com/questions/1154446/is-file-append-atomic-in-unix

There is a paper also on the same which i read in college, https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-pillai.pdf which tells that file append is not atomic on many file systems. 
When we do Set in badger and commit it, say badger writes x bytes to value log file, Multi blocks appends are not atomic in many file systems, so you can have partial data written to file.

The edited example I have now is clear proof of data loss.
If you think what TestDataLoss is simulating can't happen in real world, then all the best for your project and let's drop this discussion. You can go and ask the authors of the paper or some expert in file systems if you are still not convinced that partial append can happen in file system before crash.

**Comment by manishrjain** [comment] 2018-09-25 17:07
It is not the same. Badger has checksums in place to find if the FS has lost data, due to crash. You're writing an entry, even ensuring that it does not return an error (i.e. it has been ACKed and Fsynced to the FS), but mucking up the bits which have a certain meaning to Badger.

```
// This part simulates badger crashing before writing bitFinTx
	e := &Entry{
		Key: y.KeyWithTs([]byte(key(0)), kv.orc.nextTxnTs),
		meta: bitTxn,
		Value: []byte(data),
	}
	kv.orc.nextTxnTs++
	err = kv.batchSet([]*Entry{e})
	require.NoError(t, err)
```

If you find a way to reproduce this using public APIs, feel free to file a new issue. I'm closing this one.

**Closed by manishrjain** 2018-09-25 17:07 UTC
Labels: investigate
