### ISSUE TITLE
Return proper error if database is closed

### ISSUE THREAD

**Issue by C-ollins** [dgraph-io/badger#838] opened 2019-05-30 07:38 UTC
I get this crash whenever I try to perform operations on a closed db, what I expect is an error that can be handled from my end. I use the database from multiple threads and once it's closed I would want to reject any read/write operation but there's currently no way to check if the database is opened or not. I use a variable to tract whether the database is open or not but this does not work effectively because a thread can try to perform an operation while the database is closing and it also results in a crash.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ea06c45]
goroutine 1086 [running]:
github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger/skl/skl.go:86
github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger.(*DB).getMemTables(0x36c00700, 0x0, 0x0, 0x0, 0x0)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger/db.go:475 +0xc5
github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger.(*DB).get(0x36c00700, 0x3cf14020, 0xe, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger/db.go:499 +0x4d
github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger.(*Txn).Get(0x3c0d6300, 0x7f4ed6f0, 0x6, 0x6, 0x7ef3fa00, 0x36d4ae50, 0x7ef3fa00)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/vendor/github.com/dgraph-io/badger/transaction.go:409 +0xb6
github.com/raedahgroup/dcrlibwallet/badgerdb.(*transaction).ReadWriteBucket(0x3bf64fa0, 0x7f4ed6f0, 0x6, 0x6, 0x7ef3fa00, 0x36d4ae90)
	/Users/collins/go/src/github.com/raedahgroup/dcrlibwallet/badgerdb/db.go:66 +0x8f
```

**Comment by campoy** [comment] 2019-05-30 18:59
Thanks for your report, @C-ollins!

This seems like a good enhancement on our side, but in the meantime you could also use a Mutex to avoid the issue as a workaround.

**Comment by manishrjain** [comment] 2019-05-30 19:20
We had a similar discussion earlier. It requires a lot of changes on all the endpoints of Badger to determine if Badger is open or closed and how these would interact with each other. All the assumptions about what's running start to fail during the closing sequence. We decided it is best for the user to ensure that they finish their read/writes before closing Badger, instead of us protecting every endpoint against what we consider a user responsibility.

https://github.com/dgraph-io/badger/pull/437#issuecomment-374119127

CC: @campoy

**Comment by campoy** [comment] 2019-06-13 21:42
Closing since it works as intended.

**Closed by campoy** 2019-06-13 21:42 UTC
Labels: area/crash, kind/bug, priority/P2, status/accepted
